3. MHD NOUR EDDIN BASSAL-02210201517

In [3]:
from random import randint 
n=int(input())
liste=[randint(1,8) for i in range(n)]
#liste=[5, 8, 1, 0, 0, 5, 6]
print(liste)
def g(k,a):
    toplam=0
    c=2
    for p in range(len(k)-1): 

        y=[]
        for j in range(len(k)-p-1):
            top=0
            for i in range(j,c+j):
                top+=k[i]
            y.append(top)

        c+=1
        print(y)
        for h in y:
            if h >a:
                break
        else :
            toplam+=1
    for h in k:
        if h >a and h==a:
            break
    else :
        toplam+=1
    return toplam
l=int(input())            
print(g(liste,l))
#çözülmüş

10
[8, 4, 3, 4, 4, 6, 5, 3, 2, 3]
20
[12, 7, 7, 8, 10, 11, 8, 5, 5]
[15, 11, 11, 14, 15, 14, 10, 8]
[19, 15, 17, 19, 18, 16, 13]
[23, 21, 22, 22, 20, 19]
[29, 26, 25, 24, 23]
[34, 29, 27, 27]
[37, 31, 30]
[39, 34]
[42]
4


In [2]:
#1-2+3-4+5-6... -10
s=0
for i in range(1,11):
    if i%2==1:
        s+=1/i 
    else :  
        s-=1/i
        
print(s)
#çözülmüş

0.6456349206349207


In [3]:
def aflk (a):
    çarp =1
    for i in range (1,a+1):
        çarp*=i
    return çarp
s=0
t=int(input("biri sayı giriniz"))
for i in range (t+1):
    s+=aflk(i)
    print(str(i),"=",str(aflk(i)))
print(s)    
        
#çözülmüş

biri sayı giriniz3
0 = 1
1 = 1
2 = 2
3 = 6
10


In [7]:
def fak (a):
    çarp =1
    for i in range (1,a+1):
        çarp*=i
    return çarp
s=0
t=int(input("biri sayı giriniz : "))
for i in range (1,t+1):
    if i%2==1:
        s-=(i+fak(i+1))   
    else :
        s+=(i+fak(i+1))
print(s)

#çözülmüş

biri sayı giriniz : 6
4423


In [21]:
def fak (a):
    çarp =1
    for i in range (1,a+1):
        çarp*=i
    return çarp
s=0
t=int(input("biri sayı giriniz : "))
for i in range (1,t+1):
    if i%2==1:
        s+=i**i
    else :
        s+=(1/fak(i))
print(s)
#çözülmüş

biri sayı giriniz : 4
28.541666666666668


In [2]:
for i in range(1,6):
    print("*"*i)

*
**
***
****
*****


In [10]:
n = 0
while n <= 0:
    n = int(input("Enter the number of lines: "))
for i in range(1, n+1):
    print(" "*(n-i)+"*"*i)


Enter the number of lines: -4
Enter the number of lines: 7
      *
     **
    ***
   ****
  *****
 ******
*******


In [12]:
n = 0
while n <= 0:
    n = int(input("Enter the number of lines: "))
for i in range(n,0,-1):
    print("*"*i)

Enter the number of lines: -8
Enter the number of lines: 5
*****
****
***
**
*


In [17]:
kere=int(input("kaç kefe yazdırmak istiyorsunuz: "))
n = 0
while n <= 0:
    n = int(input("Enter the number of lines: "))
for j in range(kere):
    print(" "*(kere-j)+"*"*n)
  

kaç kefe yazdırmak istiyorsunuz: 5
Enter the number of lines: 10
     **********
    **********
   **********
  **********
 **********


In [18]:
kere=int(input("kaç kefe yazdırmak istiyorsunuz: "))
n = 0
while n <= 0:
    n = int(input("Enter the number of lines: "))
for j in range(kere):
    print(" "*j+"*"*n+" "*(kere-j))
  

kaç kefe yazdırmak istiyorsunuz: 5
Enter the number of lines: 10
**********     
 **********    
  **********   
   **********  
    ********** 


In [51]:
n = 0
while n <= 0 or n % 2 == 0:
    n = int(input("Enter the number of lines: "))
for i in range(1, n + 1):
    if i <= n / 2:
        print('*' * i, end='')
    else:
        print('*' * (n - i + 1), end='')
    print()

Enter the number of lines: 6
Enter the number of lines: 5
*
**
***
**
*


In [17]:
c=0
while n <= 0 or n % 2 == 0:
    n = int(input("Enter the number of lines: "))
for i in range(1,n+1):
    if i <= n / 2:
        print(' ' * (int(n / 2) - i + 1), end='')
        print('*', end='')
        print(' ' * ((i * 2) - 3), end='')
        if i != 1:
            print('*', end='')
    else:
        print(' ' * (i - int(n / 2) - 1), end='')
        print('*', end='')
        print(' ' * ((n * 2) - (i * 2) - 1), end='')
        if i != n:
            print('*', end='')
    print()

   *
  * *
 *   *
*     *
 *   *
  * *
   *


In [21]:
rakam=int(input())
o=rakam
sayı=""
k=str(rakam)
index=len(k)
c=0
while c<index:
    y=rakam%10
    rakam=rakam//10
    c+=1
    sayı+=str(y)
    
print(sayı)
if o==int(sayı):
    print("Palindrome")
else:
    print("Palindrome değil")


55
55
Palindrome


In [1]:
def ters(k):
    d=""
    c=0
    ind=len(k)
    while c<ind and ind >=0:
        d+=k[ind-1]
        ind-=1
    return d
oo=input("bir string giriniz: ")
print(ters(oo))

        

bir string giriniz: öhd nour e
e ruon dhö


In [45]:
i=int(input("ilk eleman: "))
f=int(input("eleman sayısı: "))
se=int(input("artış değeri: "))
top=0
sayı=i
c=1
for i in range(f):
    if c<f:
        top+=sayı
        print(sayı,end=" + ")
        sayı+=se
        c+=1
    else:
        print(sayı,end=" = ")
        top +=sayı
print(top)
        
    
    

ilk eleman: 5
eleman sayısı: 4
artış değeri: 6
5 + 11 + 17 + 23 = 56


In [3]:
n=int(input("biir sayı giriniz. "))
liste=[]
c=2
while n<=1:
    print("doğal bir sayı giriniz!!!!!!   ")
    n=int(input("biir sayı giriniz. "))
while n>1:
    if n %c==0:
        n=n/c
        if c not in liste:
            liste.append(c)
    else:
        c+=1
print(liste)
for i in liste:
    print(i)
        
            
        

biir sayı giriniz. 90
[2, 3, 5]
2
3
5


In [82]:
n=int(input("biir sayı giriniz. "))
def top(s):
    top=0
    st=str(s)
    for i in st:
        top+=int(i)
    return top
for i in range(1,n+1):
    if i%top(i)==0:
        print(f"harshad sayıdır {i} ve basamakların toplamı ={top(i)}")
    else:
        print(f"harshad değil sayıdır {i} ve basamakların toplamı ={top(i)}")

        

biir sayı giriniz. 3
harshad sayıdır 1 ve basamakların toplamı =1
harshad sayıdır 2 ve basamakların toplamı =2
harshad sayıdır 3 ve basamakların toplamı =3


In [84]:
i="  nour"
print(i.index("n"))

2


In [88]:
print(range(0,9,1))

range(0, 9)


In [5]:
i="mhd nour eddin bassal"
t=""
for j in i:
    if j =="u":
        continue 
    else:
        t+=j
print(t)

mhd nor eddin bassal


In [111]:
p=lambda p1,p2:p1+p2
print(p(4,6))

10


In [15]:
def fak(sayı):
    if sayı<0:
        print("lütfen doğal bir sayı giriniz!!! ")
    else:
        çarp=1 
        for i in range(1,sayı+1):
            çarp*=i
        return çarp
n=0
while 0<=n :
    n=int(input("bir sayı giriniz: "))
    print(fak(n))

bir sayı girininiz: 5
120
bir sayı girininiz: 3
6
bir sayı girininiz: -0
1
bir sayı girininiz: -8
lütfen doğal bir sayı giriniz!!! 
None


In [44]:
from random import randint as py
print([[py(1,9)for i in range(4)]for i in range(4)])

[[6, 3, 3, 2], [3, 1, 9, 1], [9, 8, 4, 9], [4, 8, 4, 5]]


In [46]:
k=[[py(1,9)for i in range(4)]for i in range(4)]
for i in k:
    for j in i:
        print(j,end=" ")
    print()

7 9 9 2 
5 6 3 7 
5 2 2 7 
1 7 6 8 


In [87]:
def digit(t):
    su=0
    while t>0:
        su+=t%10
        t=t//10
    return su
liste=[222,34,55,27,33]
liset1=[323,654,56,56]
f=list(map(digit,liset1))
w=list(map(digit,liste))
print(w)
print(f)

[6, 7, 10, 9, 6]
[8, 15, 11, 11]


In [70]:
from random import randint as py
o=int(input("bir sayı: "))
liste=[py(1,9)for i in range(o)]
print(f"ilk listemiz {liste} ")
list1=[]
for i in liste:
    say=0
    for j in liste:
        if i==j:
            say+=1
    list1.append(say)
print(f"sayılama listemiz {list1}")
enb=list1[0]
for i in list1:
    if i>enb:
        enb=i
print(enb)
def say(lis,sa):
    s=0
    for i in lis:
        if i==sa:
            s+=1
    return s
list2=[]
for j in liste:
    if say(liste,j)==enb:
        continue 
    else :
        list2.append(j)
print(list2)
print(len(list2))

bir sayı: 10
ilk listemiz [1, 6, 7, 2, 6, 1, 4, 4, 1, 3] 
sayılama listemiz [3, 2, 1, 1, 2, 3, 2, 2, 3, 1]
3
[6, 7, 2, 6, 4, 4, 3]
7


In [72]:
k=input().split()
print(k)

mhd nour eddin bassal
['mhd', 'nour', 'eddin', 'bassal']


In [71]:
print(chr(98)) 

b


In [104]:
def remove_all(s1, s2):

    s1_length = len(s1)
    s2_length = len(s2)
    new_string = ''

    i = 0
    while i < s1_length:

        if i <= s1_length - s2_length and s1[i: i + s2_length] == s2:
            i += s2_length

        else:
            new_string += s1[i]
            i += 1

    return new_string


text = "I like cats. I have one cat."
keyword = "cat"
newText = remove_all(text, keyword)

print("Before:", text)
print("After: ", newText)

Before: I like cats. I have one cat.
After:  I like s. I have one .


In [107]:
def reb(s1,s2,s3):
    u1=len(s1)
    u2=len(s2)
    s4=""
    i=0
    while i<u1:
        if s1[i:i+u2]==s2:
            s4+=s3
            i+=u2
        else:
            s4+=s1[i]
            i+=1
    return s4
text = "I like cats. I have one cat."
keyword = "cat"
o="dog"
print(text)
print(reb(text,keyword,o))
            
            
            


I like cats. I have one cat.
I like dogs. I have one dog.


In [108]:
def DoubleChars(st):
    st1=""
    for i in range(len(st)):
        for j in range(2):
            st1+=st[i]
    return st1
r="Iron Man"
print(r)
print(DoubleChars(r))

Iron Man
IIrroonn  MMaann


In [120]:
def bul(s1,s2):
    for i in range(len(s1)):
        if s1[i]==s2:
            print(f"{s2} found at index: {i}")
bul("Harmash is the best site to learn programming","a")

a found at index: 1
a found at index: 4
a found at index: 30
a found at index: 39


In [134]:
s="Programming is    nour to learn."
u=s.split()
print(u)

['Programming', 'is', 'nour', 'to', 'learn.']


In [2]:
def kaç(t):
    k=0
    for i in range(len(t)-1):
        if ord(t[i])>ord("A") and ord(t[i])<ord("z") or  ord(t[i])== ord(" "):
            k+=1
    return k
text = "Hi Lora.\nHow are you?."
print(kaç(text))

18


In [1]:
st="I am happy. I am a doctor. I like chocolate."
print(st)
st1=st.split()
print(st1)
l=[]
for i in st1:
    if i not in l:
        l.append(i)
print(l)
def h(j):
    cout=0
    for i in st1:
        if i==j:
            cout+=1
    return cout
for i in l:
    print(f"{[h(i)]} {i}")

I am happy. I am a doctor. I like chocolate.
['I', 'am', 'happy.', 'I', 'am', 'a', 'doctor.', 'I', 'like', 'chocolate.']
['I', 'am', 'happy.', 'a', 'doctor.', 'like', 'chocolate.']
[3] I
[2] am
[1] happy.
[1] a
[1] doctor.
[1] like
[1] chocolate.


In [16]:
def find(st,stt):
    for i in range(len(st)):
        if st[i]==stt:
            print(f"'{stt}' found at index: {i}")
k=[1, 2, 3, 2, 5, 2, 7, 2]
t=2
find(k,t)

'2' found at index: 1
'2' found at index: 3
'2' found at index: 5
'2' found at index: 7


In [36]:
# هنا قمنا بتعريف الدالة
def count_occurrence(arr):

    for i in range(0, len(arr)):

        counter = 1

        if arr[i] !="":

            for j in range(i+1, len(arr)):

                if arr[i] == arr[j]:
                    counter += 1
                    arr[j] = ""

            print("[" + str(arr[i]) + "] is repeated " + str(counter) + " time(s)")


# هنا قمنا بتجهيز القيم التي سنمررها للدالة
array = [0, 4, 2, 3, 2, 4, 3, 5, 2, 0, 1, 4, 2]

# هنا قمنا بتجربة الدالة
count_occurrence(array)

[0] is repeated 2 time(s)
[4] is repeated 3 time(s)
[2] is repeated 4 time(s)
[3] is repeated 2 time(s)
[5] is repeated 1 time(s)
[1] is repeated 1 time(s)


In [21]:
from copy import copy as co
liste=[i for i in range(1,5)]
print(liste)
li=co(liste)
del li[0:2]
print(li)
print(liste)

[1, 2, 3, 4]
[3, 4]
[1, 2, 3, 4]


In [22]:
liste=[i for i in range(1,5)]
print(liste)
li=liste
del li[:2]
print(li)
print(liste)

[1, 2, 3, 4]
[3, 4]
[3, 4]


In [51]:
methods = ['Arabic', 'English', 'Science', 'Math']
total_methods = len(methods)

notes = [-2] * len(methods)
avg = 0

for i in range(0, total_methods):
    while notes[i] < 0 or notes[i] > 20:
        notes[i] = int(input('Enter ' + methods[i] + ' note: '))

for i in range(0, total_methods):
    avg += notes[i]

avg /= total_methods

print('\nAverage:', avg, end=' ')

if avg >= 10:
    print('[ Succeeded ]')
else:
    print('[ Failed ]')

Enter Arabic note: 23
Enter Arabic note: 15
Enter English note: 12
Enter Science note: 13
Enter Math note: 11

Average: 12.75 [ Succeeded ]


In [2]:
satır=3
sutun=3
matrix=[[0 for i in range(sutun)] for j in range(satır)]
print(matrix)
to=[]
for i in range(satır):
    top=0
    for j in range(sutun):
        matrix[i][j]=int(input(f"Enter matrix[{i}][{j}]: "))
        top+=matrix[i][j]
    to.append(top)
for i in range(satır):
    for j in range(sutun):
        print(matrix[i][j], end=" ")
    print()
for i in range(len(to)):
    print(f"{i}. satırın toplamı=={to[i]}")

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
Enter matrix[0][0]: 1
Enter matrix[0][1]: 2
Enter matrix[0][2]: 3
Enter matrix[1][0]: 4
Enter matrix[1][1]: 5
Enter matrix[1][2]: 6
Enter matrix[2][0]: 7
Enter matrix[2][1]: 8
Enter matrix[2][2]: 9
1 2 3 
4 5 6 
7 8 9 
0. satırın toplamı==6
1. satırın toplamı==15
2. satırın toplamı==24


In [14]:
from random import randint as py
def arama(mat,rak):
    p=False
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            if mat[i][j]==rak:
                p=True
                break
    return p
matrix=[[py(1,9)for i in range(3)]for j in range(3)]
print(matrix)
k=9
if arama(matrix,k):
    print("bulundu")
else:
    print("hayır")
    

[[4, 4, 2], [5, 6, 2], [5, 7, 1]]
hayır


In [5]:
from random import randint as py
import numpy as k
def arama(mat):
    k=[]
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            k.append(mat[i][j])
    for i in range(len(k)-1):
        for j in range(len(k)-1):
            if k[j]>k[j+1]:
                k[j],k[j+1]=k[j+1],k[j]
    return k
def ol(mat,y):
    satır=y[0]
    sutun=y[1]
    matris=[]
    k=0
    for i in range(satır):
        st=[]
        for j in range(sutun):
            st.append(mat[k])
            k+=1
        matris.append(st)
    return matris        
    
matrix=[[py(1,9)for i in range(3)]for j in range(3)]
print(matrix)

print(arama(matrix))
print(ol(arama(matrix),(3,3)))
y=ol(arama(matrix),(3,3))
s=k.array(y)
print(s)
    

[[5, 8, 7], [4, 3, 4], [1, 5, 6]]
[1, 3, 4, 4, 5, 5, 6, 7, 8]
[[1, 3, 4], [4, 5, 5], [6, 7, 8]]
[[1 3 4]
 [4 5 5]
 [6 7 8]]


In [10]:
matrix = [
    [5, 2, 4],
    [1, 7, 3],
    [9, 8, 6]
]

rows = len(matrix)
cols = len(matrix[0])

array = [0] * (rows * cols)

print('Matrix before sorting ')

for i in range(rows):
    for j in range(len(matrix[0])):
        print(matrix[i][j], end=' ')
    print()

for i in range(rows):
    for j in range(cols):
        array[j + (i * rows)] = matrix[i][j]
print(array)

for i in range(len(array) - 1):
    for j in range(i + 1, len(array)):
        if array[j] < array[i]:
            array[j],array[i]=array[i],array[j]
print(array)
for i in range(rows):
    for j in range(cols):
        matrix[i][j] = array[j + (i * rows)]

print('\nMatrix after sorting ')

for i in range(rows):
    for j in range(cols):
        print(matrix[i][j], end=' ')
    print() 
#ikinci yol

Matrix before sorting 
5 2 4 
1 7 3 
9 8 6 
[5, 2, 4, 1, 7, 3, 9, 8, 6]
[1, 2, 3, 4, 5, 6, 7, 8, 9]

Matrix after sorting 
1 2 3 
4 5 6 
7 8 9 


In [3]:
from random import randint as py
import numpy as k
satır=int(input())
sutun=int(input())
matrix=[[py(-9,9)for i in range(sutun)]for j in range(satır)]
print(k.array(matrix))
p=0
n=0
s=0
for i in range(len(matrix)):
    for j in range(len(matrix)):
        if matrix[i][j]<0:
            n+=1
        elif  matrix[i][j]>0:
            p+=1
        else:
            s+=1
print(f"\npozitif sayısı={p}\nnegatif sayısı={n}\nsıfır sayısı={s}")

5
5
[[-1  6  2  8 -1]
 [ 2 -8  5  3  6]
 [ 6  3  3  9 -3]
 [-1  8 -3  6  7]
 [-3  8 -5  5 -4]]

pozitif sayısı=16
negatif sayısı=9
sıfır sayısı=0


In [13]:
satır=3
sutun=3
matrix=[[py(1,9) for i in range(sutun)] for j in range(satır)]
print(matrix)
s=k.array(matrix)
print(s)
abone=0
on=0
under=0
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        if i==j:
            on+=matrix[i][j]
        elif i<j:
            abone+=matrix[i][j]
            under+=matrix[j][i]
print(f"\n köşegenin üstünde={abone}\n köşegenin altında={under}\n köşegenin(diyagonal)={on}")


[[9, 7, 8], [4, 3, 1], [3, 3, 3]]
[[9 7 8]
 [4 3 1]
 [3 3 3]]

 köşegenin üstünde=16
 köşegenin altında=10
 köşegenin(diyagonal)=15


In [16]:
def PrintSecondBiggest(k):
    for i in range(len(k)-1):
        for j in range(len(k)-1):
            if k[j]>k[j+1]:
                k[j],k[j+1]=k[j+1],k[j]
    return k[-2]
arr = [5, 9, 3, 6, 4, 2, 7, 1, 8]
K=PrintSecondBiggest(arr)
print(K)

8


In [37]:
# print_second_biggest() هنا قمنا بتعريف الدالة
from random import randint as py
def print_second_biggest(arr):

    if len(arr) == 0:
        print("Invalid params")
        return

    second_biggest = arr[0]
    print(second_biggest)

    for i in range(len(arr) - 1):
        for j in range(i+1, len(arr)):
            if arr[i] > arr[j]:
                temp = arr[j]
                arr[j] = arr[i]
                arr[i] = temp
    print(arr)
    for i in range(len(arr) - 1, 0, -1):
        if arr[i] != arr[len(arr) - 1]:
            second_biggest = arr[i]
            break

    if second_biggest == arr[0]:
        print("There isn't a second biggest number")
        return
    
    print("Second biggest number is:", second_biggest)


# print_second_biggest() هنا قمنا بإنشاء مصفوفة أرقام أحادية و تجربة الدالة
arr = [py(1,9)for i in range(9)]
print(arr)
print_second_biggest(arr)

[3, 6, 5, 8, 1, 1, 9, 4, 6]
3
[1, 1, 3, 4, 5, 6, 6, 8, 9]
Second biggest number is: 8


In [52]:
def PrintLongestName(liste):
    enb=len(liste[0])
    k=liste[0]
    for i in range(len(liste)):
        if len(liste[i])>enb:
            enb=len(liste[i])
            k=liste[i]
    print(f"en uzun kelime ={k} ve onun uzunluğu ={enb}")
names = ["Mhamad", "Abdullah", "Rami", "Zeina", "Marwa"]
PrintLongestName(names)
            

en uzun kelime =Abdullah ve onun uzunluğu =8


In [65]:
# my_يحتوي على 3 قيم, إسمه هنا قمنا بإنشاء
my= ["Banana", "Orange", "Apple"]

# my_وضعنا فيه قيم الكائن iterator هنا قمنا بإنشاء
my_iterator = iter(my)

# ثلاث مرات و عرض ما ترجعه في كل مرة next() هنا قمنا باستدعاء الدالة
# my_iterator لاحظ أنها في كل مرة ترجع القيمة التالية في الكائن
print(next(my_iterator))
print(next(my_iterator))
print(next(my_iterator))

Banana
Orange
Apple


In [12]:
# my_يحتوي على 3 قيم, إسمه هنا قمنا بإنشاء
my= ("Banana", "Orange", "Apple")

# بعدها سيتم عرض قيمته ,val و من ثم وضعها في المتغير my_هنا في كل دورة سيتم جلب القيمة التالية من الكائن
for val in my:
    print(val)

Banana
Orange
Apple


In [13]:
# __next__() و __iter__() للدالتين Override لأنه يفعل Iterator يمثل IterCounter هنا قمنا بإنشاء كلاس إسمه
class IterCounter:

    # هي 0 IterCounter هنا قلنا أن القيمة الأولى التي سيتم إعطاؤها لأي كائن يتم إنشاؤه من الكلاس
    def __iter__(self):
        self.num = 0
        return self

    # مضافاً إليها 1 num ستكون قيمة المتغير next() في كل مرة نستدعي فيها الدالة IterCounter هنا قلنا أن القيمة التالية التي سيرجعها الكائن الذي ننشئه من الكلاس
    def __next__(self):
        self.num += 1
        return self.num


# iter_counter و من ثم قمنا بتخزينه في الكائن ,iter() بواسطة الدالة iterator مع تحويله مباشرةً لـ IterCounter هنا قمنا بإنشاء كائن من الكلاس
iter_counter = iter(IterCounter())

# next() في كل مرة نمرره للدالة iter_counter هنا قمنا بعرض القيمة التالية التي سيرجعها الكائن
for i in range(6):
    print(next(iter_counter))

1
2
3
4
5
6


In [86]:
class PowTwo:

    # يمكن تمرير رقم لها مباشرةً عند إنشاء كائن من هذا الكلاس end الخاصية
    def __init__(self, end=1):
        self.end = end

    # تساوي 0 next() الذي سنستخدمه لحساب كم مرة تم إستدعاء الدالة n هنا جعلنا القيمة الأولية للمتغير
    def __iter__(self):
        self.n = 1
        return self

    # سيتم إرجاع القيمة  end أصغر من قيمة الخاصية n إذا كانت قيمة المتغير ,next() هنا قلنا أنه كلما تم إستدعاء الدالة
    # الذي يعني أنه لم يعد هناك أي قيمة في الكائن StopIteration المضاعفة التالية, و إذا لم تكن أصغر منها سيتم إرجاع الخطأ
    def __next__(self):
        if self.n <= self.end:
            result = 2 ** self.n
            self.n += 1
            return result
        else:
            raise StopIteration


# next() و من ثم طباعة المضاعفات الخمسة للرقم 2 كلما تم إستدعاء الدالة end و تمرير القيمة 5 مكان الخاصية  PowTwo هنا قمنا بإنشاء كائن من الكلاس
for val in PowTwo(5):
    print(val)

2
4
8
16
32


In [26]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits

print(x)
print(y)
print(z)


apple
banana
cherry


In [15]:
def asalmı(sayı):
    k=True
    for i in range(2,sayı):
        if sayı%i==0:
            k=False
            break
    return k
n=int(input("bir sayı giriniz: "))
for i in range(2,n):
    if asalmı(i)==True:
        print(i)

bir sayı giriniz: 33
2
3
5
7
11
13
17
19
23
29
31


In [1]:
n=int(input("hangi sayı ile başlayacağnı yazınız: "))
a=list(range(1,n+1));print(a)
def j(f):
    t=[]
    top=0
    for i in range(2):
        t.append(f[i])
    if t[0]==0:
        for i in a:
            if i>=t[1]:
                top+=1
    elif t[0]==1:
        for i in a:
            if i>t[1]:
                top+=1
    return top
q=int(input(("kaç sayı olacağını yazınız: ")))
o=[]
for i in range(q):
    w=list(map(int,input().split()))
    o.append(j(w))
for i in o:
    print(i)
    

hangi sayı ile başlayacağnı yazınız: 4
[1, 2, 3, 4]
kaç sayı olacağını yazınız: 3
0 5
1 3
0 3
0
1
2


In [3]:
T=int(input())
liste=[]
for ı in range(T):
    x=list(map(int,input().split()))
    while True:
        L=x[0];R=x[1];
        if R>L and L>=1:
            count=0
            if L==1:
                for i in range(L+1,R+1):
                    count+=1
                liste.append(count)
                break
            else:
                for i in range(L,R+1):
                    count+=1
                liste.append(count)
                break
        else:
            x=list(map(int,input().split()))
print(liste)
for i in liste:
    print(i)
    

3
1 3
5 8
7 12
[2, 4, 6]
2
4
6


In [26]:
def k(sayı,n):
    f=[]
    while sayı>0:
        m=sayı%n
        sayı=int(sayı/n)
        f.append(str(m))
    f.reverse()
    y="".join(f)
    return int(y)
sayı=int(input())
taban=int(input())

print(f"\n girdimiz sayı={sayı} ve taban={taban} dolaysıyla sayının {taban}. tabana çevirdiğimiz zaman ={k(sayı,taban)}")

    
    

12
2

 girdimiz sayı=12 ve taban=2 dolaysıyla sayının 2. tabana çevirdiğimiz zaman =1100


In [61]:
T=int(input())
for i in range(T):
    m=list(map(int,input().split()))
    a=m[0];b=m[1];k=m[2];
    st=""
    top=a
    for i in range(k):
        st+=str(top)
        top+=b
    print(st[k-1])
    

2
3 5 9
2
2 7 10
7


In [67]:
from random import randint as py
x="31415926"
n=len(x)
p=""
m=int(input())
for i in range(m):
    o=""
    s=list(map(int,input().split()))
    k=s[0];l=s[1];
    if k>=l:
        for ı in range(k):
            o+=x[py(0,n-1)]
        p+=o[l-1]
    else:
        pass
    
print(p)
    
    


2
3 4
3 3
6


In [20]:
from random import randint as py
l=[i for i in range(1,6)]
print(l)
p=int(input())
for i in range(1,p+1):
    l[0:i]=[0 for i in range(i)]
    l.append(py(1,9))
    print(l)
    
    


[1, 2, 3, 4, 5]
2
[0, 2, 3, 4, 5, 6]
[0, 0, 3, 4, 5, 6, 1]


In [29]:
l=[i for i in range(1,6)]
print(l)
l[0:3]=[0 for i in range(3)]
print(l)

[1, 2, 3, 4, 5]
[0, 0, 0, 4, 5]


In [30]:
def k(sayı):
    sayı *=2
    print(sayı)
    def j(sa):
        top =0
        for i in range(1,sa+1):
            top+=i
        return top
    print(j(sayı))
print("nour eddın bassal")
while True:
    o=int(input())
    k(o)
    if o==6:
        break

nour eddın bassal
3
6
21
4
8
36
6
12
78


In [3]:
def enqueue(element):
    global queue,front,rear,arraySize
    if(rear == arraySize):
        print("Tam dolu")
    else:
        queue.append(element)        
        rear+=1    
        print(rear-front)    

def dequeue():
    global queue,front,rear,arraySize
    if(front == rear):           
        print("-1 0")
    else:
        c = queue[front]
        queue[front] = 0       
        front+=1
        print(c," ",rear-front)                        
front = 0; rear = 0;
arraySize = 100
queue = []
N = int(input())
for i in range(N):
    txt = input().split()#["E","5"]
    if txt[0]=='D':        
        dequeue()
    else:    
        enqueue(txt[1])
print(queue)

4
E 2
1
E 4
2
E 1
3
D
2   2
[0, '4', '1']


In [11]:
def k(sa):
    liste=[]
    for i in str(sa):
        liste.append(i)
    liste.reverse()
    liste="".join(liste)
    return liste
    
    
sayı=int(input())
print()
s=sayı
for t in range(len(str(sayı))):
    s=sayı
    print(s)
    print(k(s))
    sayı=int(sayı/10)

    

13475

13475
57431
1347
7431
134
431
13
31
1
1


In [ ]:
top=0
sayı=0
while True:
    k=int(input())
    for i in range(k):
        top+=int(input())
        sayı+=1
    print(top/sayı)

2
6
8
7.0
2
10
8
8.0


In [30]:
def ksd(sayı):
    sayı1=str(sayı)
    k1=True
    uzunluk=len(sayı1)
    for i in range(uzunluk//2):
        if sayı1[i]!=sayı1[uzunluk-i-1]:
            k1=False                                   #1234321
            break
    return k1
    
j=int(input())
s=j

while j>=0:
    if ksd(j)==True:
        print(j)
        break
    else:
        j-=1
print(s-j)

123
121
2


In [1]:
from random import randint as ra
def le(li):
    enb=0
    for i in range(len(li)):
        l=[]
        l.append(li[i])
        j=li[i]
        for u in range(len(li)):
            for o in range(len(li)):
                if j==li[o]-1 :
                    l.append(li[o])
                    j=li[o]
            if len(l)>enb:
                enb=len(l)
                k=l

    return enb,k
                
k=int(input())
liste=[ra(1,25)for i in range(k)]
#
print(liste)
print(f"\n en uzun ardışık dizi {le(liste)[0]} ve listemiz :{le(liste)[1]}")

15
[18, 4, 5, 2, 21, 6, 22, 10, 12, 13, 17, 7, 5, 14, 14]

 en uzun ardışık dizi 4 ve listemiz :[4, 5, 6, 7]


In [134]:
from random import randint
import numpy
ss=int(input())
matrix=numpy.random.randint(0,2,(ss,ss))
print(matrix) 
kaç_tane=0
for i in range(ss-1):
    for j in range(ss-1):
        top=0
        for o in range(2):
            for ş in range(2):
                top+=matrix[i+o][j+ş]
        if top==4:
            kaç_tane+=1
print(kaç_tane)
            

5
[[0 1 0 1 1]
 [1 0 0 1 0]
 [1 1 1 0 0]
 [0 1 1 1 1]
 [0 1 1 0 0]]
2


In [4]:
yeni=[0,1,0,2,12]
yeni_liste=[0]*len(liste)
print(yeni_liste)
s=1
r=0
for i in range(len(liste)):
    if yeni[i]!=0:
        yeni_liste[r]=yeni[i]
        r+=1
    else:
        yeni_liste[-s]=yeni[i]
        s+=1
print(yeni_liste)
        

[0, 0, 0, 0, 0]
[1, 2, 12, 0, 0]


In [14]:
#birinci yol
from random import randint as d
def kk(lis):
    enb=sum(lis)
    c=1
    while c<len(lis):
        for i in range(len(lis)-c+1):
            li=lis[i:c+i]
            top=sum(li)
            if top>enb:
                enb=top
                k=li
        c+=1
    return enb,k
liste=[d(-5,9) for i in range(9)]
print(liste)
print(kk(liste))

[-2, 4, 3, 1, 2, -2, 8, -4, 1]
(16, [4, 3, 1, 2, -2, 8])


In [29]:
def kaç(li,t):
    count=li.count(t)
    return count
liste=input().split()
liste="".join(liste)
print(liste)
k=list(set(liste))
print(k)
l=True
for i in k:
    if i=="A":
        if kaç(liste,i)>=2:
        
            l=False
            break
    elif i=="L":
        if kaç(liste,i)>=3:
            l=False
            break

print(l)            
    
#A هي عدد التاخر و L هي الغياب اذا زدادو عن العيار المطلوب بيرسب

P P A P L L L 
PPAPLLL
['A', 'L', 'P']
False


In [5]:
from random import randint as ra
def k(li):
    global sayı
    yeniliste=[]
    t=0
    for i in range(sayı):
        lis=[]
        for j in range(i+1):
            lis.append(li[t])
            t+=1
        yeniliste.append(lis)
    return yeniliste
sayı=int(input())
liste=[ra(1,9) for i in range(int(sayı*(sayı+1)/2))]
if __name__=="__main__":
    print(liste)
    print(len(liste))
    print(k(liste))

5
[9, 8, 8, 1, 8, 9, 8, 6, 5, 2, 3, 9, 5, 4, 6]
15
[[9], [8, 8], [1, 8, 9], [8, 6, 5, 2], [3, 9, 5, 4, 6]]


In [45]:
class Node:
    def __init__(self, data = None, next=None): 
        self.data = data
        self.next = next
class LinkedList:
    def __init__(self):  
        self.head = None
    def append(self, data):
        newNode = Node(data)
        if(self.head):
            current = self.head
            while(current.next):
                current = current.next
            current.next = newNode
        else:
            self.head = newNode
    def print(self):
        current = self.head
        while(current):
            print(current.data)
            current = current.next
LL = LinkedList()
LL.append(3)
LL.append(4)
LL.append(5)
LL.print()
#linkred listin kodu

3
4
5


In [ ]:
#السؤال الفوق بكرة بشوف حلو ان شاء الله

In [12]:
import random
import time 
start=time.time()
def sıralama(li):
    for ii in range(len(li)):
        for i in range(ii+1,len(li)):
            if li[ii]>li[i]:
                li[ii],li[i]=li[i],li[ii]
    return li
def fak(sayı):
    top=1
    for i in range(1,sayı+1):
        top*=i
    return top
def index(lis):
    global target
    indexlerin_matrisi=[]
    for c in range(1,len(lis)+1):#cمنشان نجرب من 1 لل 9 مثلا اذا كانت 3 يعني بدي شوف اذا في 3 مواقع مجموعن 9
        s=[]#منشان الاعداد الجربناهن ندخلن لهون وتاكد انو مايتجربو مرة تانية
        for i in range(0,int(fak(len(lis))/(fak(c)*fak(len(lis)-c)))):
            k=random.sample(list(range(len(lis))),c)
            if k not in s and sıralama(k) not in s :
                top=0
                for i in k:
                    top+=lis[i]
                if top==target:
                    indexlerin_matrisi.append(k)
                s.append(sıralama(k))
    return indexlerin_matrisi
liste=[2,7,3,6,8,1,5,4]
target=9
print(liste)

print(index(liste))
end=time.time()
print(end-start)
#كود يعطينا مواقع لااعداد المجموعهن 9 لانو نحن اخترناه            

[2, 7, 3, 6, 8, 1, 5, 4]
[[6, 7], [0, 1], [2, 3], [0, 3, 5], [0, 2, 7]]
0.0


In [45]:
from random import randint as ra
m=int(input())
n=int(input())
nums1=[ra(1,9)for i in range(m)]+[0]*n
nums2=[ra(1,9)for i in range(n)]
print(nums1)
print(nums2)
nums3=[]
c=0
for i in range(m+n):
    if nums1[i]!=0:
        nums3.append( nums1[i])
    else:
        nums3.append(nums2[c])
        c+=1
print(sorted(nums3))
#Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
#Output: [1,2,2,3,5,6]

5
2
[3, 7, 9, 1, 4, 0, 0]
[6, 7]
[1, 3, 4, 6, 7, 7, 9]


In [1]:
class Stack():
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()

    def get_stack(self):
        return self.items

myStack = Stack()
myStack.push("A")
myStack.push("B")
print(myStack.get_stack())
myStack.push("C")
print(myStack.get_stack())
myStack.pop()
print(myStack.get_stack())

['A', 'B']
['A', 'B', 'C']
['A', 'B']


In [13]:
"""
Stack Data Structure.
"""
class Stack():
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()
    
    def is_empty(self):
        return self.items == []
    
    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        
    def get_stack(self):
        return self.items

myStack = Stack()
myStack.push("A")
myStack.push("B")
myStack.push("C")
myStack.push("D")
print(myStack.peek())

D


In [3]:
from time import time as t
start=t()
def tane(sayı):
    kaç=0
    for i in range(1,sayı+1,2):
        top=0
        j=i
        liste=[]
        while j<=sayı:
            top+=j
            liste.append(j)
            j+=2
            if top==sayı:
                kaç+=1
                print(liste)
                break
            elif top>sayı:
                break
    return kaç

sayı=int(input("bir sayı giriniz: "))
print(tane(sayı))
end=t()
print(end-start)
        

bir sayı giriniz: 45
[5, 7, 9, 11, 13]
[13, 15, 17]
[45]
3
1.776672601699829


In [4]:
from time import perf_counter 
start=perf_counter()
def fak(sayı):
    top=1
    for i in range(1,sayı+1):
        top*=i
    return top
def sıfır(sayı):
    count=0
    sayı=str(sayı)
    k="".join([sayı[i] for i in range(len(sayı)-1,-1,-1)])
    for i in k:
        if int(i)==0:
            count+=1
        else:
            break
    return count
t=int(input())
liste=list()
fak_liste=list()
for i in range(t):
    n=int(input("bir sayı giriniz: "))
    faktöryel=fak(n)
    fak_liste.append(faktöryel)
    liste.append(sıfır(faktöryel))
print(fak_liste)
print(liste)
end=perf_counter()
print(end-start)
print(int(end-start))
#سؤال بدي دخل عدد وهاد العدد عدد تكرارات الاعداد وهس الاعداد بناخد العاملة تبعها وبعدين بدي عدد الصفار اخر الرقم

3
bir sayı giriniz: 12
bir sayı giriniz: 5
bir sayı giriniz: 7
[479001600, 120, 5040]
[2, 1, 1]
5.962045599999982
5


In [ ]:
def böl(lis):
    kalan=0
    başla=2
    li=[]
    while başla<min(lis):
        k=True
        for i in lis:
            if i%başla!=kalan:
                k=False
                başla+=1
                break
        if k==True:
            li.append(başla)
            kalan=başla
            başla+=1
    return li
                
            
        
liste=list()
m=int(input())
for i in range(m):
    liste.append(int(input()))
print(böl(liste))
#اول مرة قسمنا على 2 تقسمو كلن بنضيفو بعدين لازم نقسم على عدد باقيه 2 وهييييك

In [64]:
str1=[];str2=[]
s = "ab#c"
t = "ad#c"
#s = "a#c"; t = "b"
for i in s:
    if i == '#':
        if str1:
            str1.pop()
    else:
        str1.append(i)
for i in t:
    if i == '#':
        if str2:
            str2.pop()
    else:
        str2.append(i)
print(str1);print(str2)
print(str1 == str2)

['a', 'c']
['a', 'c']
True


In [15]:

def binary(liste,value):
    ilk=0
    son=len(liste)
    while ilk<son:
        orta=(ilk+son)//2
        if liste[orta]==value:
            return True,orta
        elif liste[orta]>value:
            son=orta-1
        else:
            ilk=orta+1
    return False
va=int(input("bir sayı giriniz: "))
liste=list(range(1,11))
print(liste)
print(binary(liste,va))

bir sayı giriniz: 6
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
(True, 5)


In [36]:
def ternary_search(l,r,x):
    global ar
    if ar[-1]>=x:
        if r>=l:
            mid1=int(l+(r-l)/3)
            mid2=int(r-(r-l)/3)
            if ar[mid1]==x:
                return mid1
            if ar[mid2]==x:
                return mid2
            if x<ar[mid1]:
                return ternary_search(l,mid1-1,x)
            elif (x>ar[mid2]):
                return ternary_search(mid2+1,r,x)
            else:
                return ternary_search(mid1+1,mid2-1,x)
    else:
        return -1
    return -1

ar=[2,3,5,6,8,9,12,13,14]
l=0
r=len(ar)
x=int(input("bir sayı giriniz: "))
print(ternary_search(l,r,x))
    
        

bir sayı giriniz: 12
6


In [4]:
#dhfsdsh
from random import randint as ra
from time import perf_counter
start=perf_counter()
def obeb(sayı1,sayı2):
    if sayı2==0:
        return sayı1
    else:
        return obeb(sayı2,sayı1%sayı2)
def sort(liste):
    n=len(liste)
    for i in range(1,n):
        j=i
        while j>0 and liste[j-1]>liste[j]:
            liste[j-1],liste[j]=liste[j],liste[j-1]
            j-=1
    return liste
def parçalama(liste):
    size=len(liste)
    orta=size//2
    a=liste[:orta]
    b=liste[orta:]
    a_sort=sort(a)
    b_sort=sort(b)
    return  a_sort, b_sort
arr=[ra(9,25)for i in range(10)]
print(arr)
print(parçalama(arr))
c1,c2=parçalama(arr)
v=sort(c1+c2)
print(v)
s1=v[0];s2=v[-1]
print(obeb(s1,s2))
end=perf_counter()
print(end-start)


[10, 11, 10, 23, 20, 14, 15, 13, 12, 14]
([10, 10, 11, 20, 23], [12, 13, 14, 14, 15])
[10, 10, 11, 12, 13, 14, 14, 15, 20, 23]
1
0.000634399999995594


In [29]:
from random import randint as ra
from time import time 
start=time()
def insertion_sort(liste):
    n=len(liste)
    for i in range(1,n):
        j=i
        while j>0 and liste[j-1]>liste[j]:
            liste[j-1],liste[j]=liste[j],liste[j-1]
            j-=1
    return liste
def yeni_liste():
    global liste,liste1
    k=[]
    for i in range(len(liste1)):
        sayı=liste1[i]
        f=[]
        a=0
        while a<liste.count(sayı):
            f.append(liste[a])
            del liste[a]
        k.append(f)
        
    return k
liste=[ra(1,9) for i in range(10)]
liste=insertion_sort(liste)
print(liste)
liste1=list(set(liste))
print(liste1)
print(yeni_liste())
end=time()
print(end-start)

[1, 1, 2, 2, 3, 4, 6, 6, 6, 8]
[1, 2, 3, 4, 6, 8]
[[1, 1], [2, 2], [3], [4], [6, 6, 6], [8]]
0.0


In [10]:
from random import randint as ra
def qcick_sort(liste):
    if len(liste)<=1:
        return liste

    else:
        sayı=liste.pop()
    sağ=[]
    sol=[]
    for i in liste:
        if i<sayı:
            sol.append(i)
        else:
            sağ.append(i)
    return qcick_sort(sol)+[sayı]+qcick_sort(sağ)
    
liste=[ra(1,25)for i in range(9)]
print(liste)
print(qcick_sort(liste))

[12, 24, 2, 24, 15, 23, 10, 5, 1]
[1, 2, 5, 10, 12, 15, 23, 24, 24]


In [44]:
nums=[1,1,2]
visit=[]
res=[]
def backtrack(res,subset):
    global visit,nums
    if len(subset)==len(nums):
        if subset not in res:
            res.append(subset)
    for i in range(len(nums)):
        if i not in visit:
            visit.append(i)
            backtrack(res,subset+[nums[i]])
            visit.remove(i)
    return res
print(backtrack(res,[]))

[[1, 1, 2], [1, 2, 1], [2, 1, 1]]


In [4]:
nums=[1,2,3]
visit=[]
res=[]
def backtrack(subset):
    if len(subset)==len(nums):
        if subset not in res:
            res.append(subset)
    for i in range(len(nums)):
        if i not in visit:
            visit.append(i)
            backtrack(subset+[nums[i]])
            visit.remove(i)
    return res
print(backtrack([]))

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


In [61]:
#birinci yol
from random import randint 
import numpy
liste=numpy.random.randint(1,9,(2,2))
print(liste)
def doğrumu(liste):
    for i in range(len(liste[0])):#1
        for j in range(len(liste)-1):#2
            if liste[j][i]>=liste[j+1][i]:
                return False
    return True
print(doğrumu(liste))
            

[[3 1]
 [5 7]]
True


In [89]:
#ikinci yol
from random import randint 
import numpy
liste=numpy.random.randint(1,9,(3,3))
print(liste)
def can_see_stage(seats):
    for col_idx in range(len(seats[0])):
        column = [seats[row_idx][col_idx] for row_idx in range(len(seats))]
        for i in range(len(column) - 1):
            if column[i] >= column[i + 1]:
                return False
    return True
print(can_see_stage(liste))

[[2 3 2]
 [5 2 4]
 [4 1 5]]
False


In [27]:
from time import time
start=time()
def prime_factors(n):
    res = []
    for i in range(2, int(n**0.5) + 1): 
        while not n%i: 
            res.append(i) 
            n //= i
    return res + [n] if n > 1 else res
nums=int(input("bir sayı giriiniz: "))
print(prime_factors(nums))
end=time()
print(end-start)


bir sayı giriiniz: 6
[2, 3]
2.6189849376678467


In [74]:
def overlap(s1, s2):
    s3=s1
    for i in range(len(s2)+1,-1,-1):
        if s2[:i] in s3:
            s3+=s2[i:]
            break
    return s3
print(overlap("edabit", "iterate"))

edabiterate


In [98]:
def dice(num):
    dic =  {1: "---/-O-/---", 2: "O--/---/--O",
            3: "O--/-O-/--O", 4: "O-O/---/O-O",
            5: "O-O/-O-/O-O", 6: "O-O/O-O/O-O"}
    r, i = [], 1
    n = [0, 6, 5, 4, 3, 2, 1]
    while num != 0:
        if num - n[i] >= 0:
            num -= n[i]
            r.append(dic[n[i]])
        else:
            i += 1
    return ", ".join(r)
print(dice(23))

O-O/O-O/O-O, O-O/O-O/O-O, O-O/O-O/O-O, O-O/-O-/O-O


In [3]:
def dice(n):
    try:
        if n<0:
            raise "error"
        if n == 0:
            return 0
        elif n == 1:
            return "---/-O-/---"
        elif n == 2:
            return "O--/---/--O"
        elif n == 3:
            return "O--/-O-/--O"
        elif n == 4:
            return "O-O/---/O-O"
        elif n == 5:
            return "O-O/-O-/O-O"
        elif n == 6:
            return "O-O/O-O/O-O"
        elif n>6:
            return "O-O/O-O/O-O, "+dice(n-6)
    except :
        sayı=int(input("bir sayı giriniz: "))
        return dice(sayı)
        
sayı=int(input("bir sayı giriniz: "))
print(dice(sayı))

bir sayı giriniz: -8
bir sayı giriniz: -6
bir sayı giriniz: 9
O-O/O-O/O-O, O--/-O-/--O


In [1]:
def dice(n):
    d = {1: '---/-O-/---', 2: 'O--/---/--O', 3: 'O--/-O-/--O', 
         4: 'O-O/---/O-O', 5: 'O-O/-O-/O-O', 6: 'O-O/O-O/O-O'}
    i, res = 6, []
    while n:
        repeat, n = divmod(n, i)
        res += [d[i]] * repeat
        i -= 1
    return ', '.join(res)
print(dice(9))

O-O/O-O/O-O, O--/-O-/--O


In [64]:
from random import randint,shuffle
def shuffle_count(num):
    liste=[randint(1,9)for i in range(num)]
    print(liste)
    tane=0
    yeni_liste=liste[:]
    while True:
        l=[yeni_liste[0]]
        h=[yeni_liste[-1]]
        lis=yeni_liste[1:-1]
        shuffle(lis)
        yeni_liste=l+lis+h
        print(yeni_liste)
        if yeni_liste!=liste:
            tane+=1
            
        else:
            return tane
number=int(input("bir sayı giriiniz: "))
print(shuffle_count(number))

bir sayı giriiniz: 5
[7, 6, 2, 6, 1]
[7, 6, 6, 2, 1]
[7, 2, 6, 6, 1]
[7, 6, 6, 2, 1]
[7, 6, 2, 6, 1]
3


In [90]:
def shift_sentence(txt):
    liste=txt.split()
    print(liste)
    c=-1
    yeni_liste=[]
    for i in liste:
        kelime=liste[c]
        o=i.replace(i[0],kelime[0])
        yeni_liste.append(o)
        c+=1
    return " ".join(yeni_liste)
print(shift_sentence("the output is not very legible"))


['the', 'output', 'is', 'not', 'very', 'legible']
lhe tutput os iot nery vegibve


In [139]:
from random import randint as ra
import numpy
def matrix_mult(m1, m2):
    return [[sum(a*b for a,b in zip(row, col)) for col in zip(*m2)] for row in m1]
m1=numpy.random.randint(1,9,(2,2))
m2=numpy.random.randint(1,9,(2,2))
print(m1)
print(m2)
print(matrix_mult(m1,m2))

[[5 7]
 [5 4]]
[[3 6]
 [6 2]]
[[57, 44], [39, 38]]


In [42]:
def top(liste):
    toplam=0
    for i in liste:
        toplam+=i
    return toplam
        
def wrong_number(lst):
    sayı=None  
    for i in range(len(lst)):
        satır=lst[i]
        for t in range(len(lst)):
            sütun=[lst[j][t] for j in range(len(lst))] 
            top_satır=top(satır[:len(satır)-1])
            top_sütun=top(sütun[:len(sütun)-1])
            rakam=lst[i][t]
            if top_satır==satır[-1] and top_sütun==sütun[-1]:
                continue
            elif top_satır!=satır[-1] and top_sütun!=sütun[-1]:
                sayı=rakam+satır[-1]-top_satır
                return sayı
            elif top_satır!=satır[-1] and top_sütun==sütun[-1]:
                sayı=top_satır
                return sayı
            elif top_satır==satır[-1] and top_sütun!=sütun[-1]:
                sayı=top_sütun
                return sayı
lst2 = [
  [1, 2, 3, 7 ],
  [4, 5, 6, 15],
  [7, 8, 9, 24],
  [12,15,18,45]
]
print(wrong_number(lst2))

6


In [61]:
def top(liste):
    toplam=0
    for i in liste:
        toplam+=i
    return toplam
        
def min_length(lst, n):
    uzunluk=1
    while uzunluk<len(lst)+1:
        for i in range(len(lst)):
            liste=lst[i:uzunluk+i]
            if top(liste)>n:
                return uzunluk,liste
        uzunluk+=1
    return -1
print(min_length([0, 1, 1, 0], 2))        


-1


In [45]:
from random import randint as ra
liste=[ra(1,15)for i in range(15)]
size=int(input("istediğiniz uzunluğu seçin "))
yeni_liste=[]
print(liste)
while len(liste)!=0:
    if len(liste)<size:
        yeni_liste.append(liste[:len(liste)])
        liste=liste[len(liste):]
    else:
        yeni_liste.append(liste[:size])
        liste=liste[size:]
print(yeni_liste)

istediğiniz uzunluğu seçin 4
[14, 4, 7, 4, 9, 11, 4, 10, 5, 1, 3, 6, 11, 11, 4]
[[14, 4, 7, 4], [9, 11, 4, 10], [5, 1, 3, 6], [11, 11, 4]]


In [2]:
nums=[1,2,3,4]
new_list=[]
def collection(liste):
    sum=0
    for number in liste:
        sum+=number
    return sum
for number in range(len(nums)):
    liste=nums[:number+1]
    sum_of_element=collection(liste)
    new_list.append(sum_of_element)
print(new_list)

[1, 3, 6, 10]


In [3]:
nums=[1,2,3,4]
new_list=[]
sum=0
for i in nums:
    sum+=i
    new_list.append(sum)
print(new_list)

[1, 3, 6, 10]


In [11]:
from random import randint
import numpy
matrix=numpy.random.randint(1,25,(3,3))
print(matrix)
print()
liste=[list(i)for i in list(zip(*matrix))]
for i in liste:
    print(i)

[[23 14 22]
 [11  8  5]
 [ 4  3 14]]

[23, 11, 4]
[14, 8, 3]
[22, 5, 14]


In [61]:
class sumRegion:
    def __init__(self,liste):
        self.sum_liste=[]
        self.matrix=liste
    def sumregion(self,lst):
        toplam=0
        for i in range(lst[0],lst[2]+1):
            satır=[self.matrix[i][j] for j in range(lst[1],lst[3]+1)]
            toplam+=collection(satır)
        self.sum_liste.append(toplam)
    def collection(self,liste):
        sum=0
        for number in liste:
            sum+=number
        return sum
matrix=[[3, 0, 1, 4, 2], [5, 6, 3, 2, 1], [1, 2, 0, 1, 5], [4, 1, 0, 1, 7], [1, 0, 3, 0, 5]]
sumRegion=sumRegion(matrix)
lst=[1,2,2,4]
lst1=[2,1,4,3]
lst2=[1,1,2,2]
sumRegion.sumregion(lst)
sumRegion.sumregion(lst1)
sumRegion.sumregion(lst2)
print(sumRegion.sum_liste)

[12, 8, 11]


In [124]:
class NumMatrix:
    def __init__(self, matrix):
        self.dp=[[0] * (len(matrix[0])+1) for _ in range(len(matrix)+1)]
        self.küme=[]
        for r in range(len(self.dp)-1):
            for c in range(len(self.dp[0])-1):
                self.dp[r+1][c+1]=matrix[r][c] + self.dp[r][c+1] + self.dp[r+1][c] - self.dp[r][c]
        
    def sumRegion(self, row1, col1, row2, col2):
        toplam=self.dp[row2+1][col2+1] - self.dp[row1][col2+1] - self.dp[row2+1][col1] + self.dp[row1][col1]
        self.küme.append(toplam)
matrix=[[3, 0, 1, 4, 2], [5, 6, 3, 2, 1], [1, 2, 0, 1, 5], [4, 1, 0, 1, 7], [1, 0, 3, 0, 5]]
lst=[1,2,2,4]
lst1=[2,1,4,3]
lst2=[1,1,2,2]
NumMatrix=NumMatrix(matrix) 
NumMatrix.sumRegion(lst[0],lst[1],lst[2],lst[3])
NumMatrix.sumRegion(lst1[0],lst1[1],lst1[2],lst1[3])
NumMatrix.sumRegion(lst2[0],lst2[1],lst2[2],lst2[3])
sum_küme=NumMatrix.küme
print(sum_küme)
#هاد الحل اسطوري

[12, 8, 11]


In [1]:
from time import time
start=time()
def solvenqueens(n):
    col=set()
    pos=set()
    neg=set()
    res=[]
    board=[["."]*n for i in range(n)]
    
    
    def backtrack(r):
        if r==n:
            copy=["".join(row) for row in board]
            res.append(copy)
            return
        
        
        for c in range(n):
            if c in col or (r+c)in pos or (r-c)in neg:
                continue
            col.add(c)
            pos.add(r+c)
            neg.add(r-c)
            board[r][c]="Q"
            
            
            backtrack(r+1)
            
            
            col.remove(c)
            pos.remove(r+c)
            neg.remove(r-c)
            board[r][c]="."
    backtrack(0)
    return res

print(solvenqueens(4))
end=time()
print(end-start)
            


[['.Q..', '...Q', 'Q...', '..Q.'], ['..Q.', 'Q...', '...Q', '.Q..']]
0.0


In [27]:
class Solution:
    
    def __init__(self):
        self.ans = 0
        
    def recurse(self,visited,ind):
           
        for i in range(self.n):
            
            if visited[ind][i] == False:
             
                if ind == self.n-1:
                    self.ans += 1
                    return
                
                new = [visited[h][:] for h in range(self.n)]
                for k in range(self.n):
                    new[ind][k] = True
                    new[k][i] = True
                    
                for r,c in {(1,1),(-1,-1),(1,-1),(-1,1)}:
                    ar,ac = ind + r,i + c
                    while 0 <= ar < self.n and 0 <= ac < self.n:
                        new[ar][ac] = True
                        ar,ac = ar+r,ac+c
                self.recurse(new,ind+1)
                
    def totalNQueens(self, n: int) -> int:
        self.n = n
        visited = [[False]*n for _ in range(n)]
        self.recurse(visited,0)
        return self.ans
Solution=Solution()
print(Solution.totalNQueens(4))

2


In [25]:
 s = "pwwkew"
def aynasımı(liste):
    for i in range(len(liste)):
        for j in range(i+1,len(liste)):
            if liste[i]==liste[j]:
                return False
    return True
def lst(s):
    sk=(" ".join(s)).split()
    print(sk)
    length=len(sk)
    while length>=1 :
        for i in range(0,len(sk)-length+1):
            liste=sk[i:i+length]
            ayna=aynasımı(liste)
            if ayna:
                kelime="".join(liste)
                return kelime,len(kelime)

        length-=1
print(lst(s))

['p', 'w', 'w', 'k', 'e', 'w']
('wke', 3)


In [32]:
from collections import deque

class Solution:
    def lengthOfLongestSubstring(self, s):
        """
        :type s: str
        :rtype: int
        """
        q = deque()
        items = {}
        maxLen = 0
        
        for c in s:
            if c in items:
                poppedItem = None
                while poppedItem != c:
                    poppedItem = q.popleft()
                    if poppedItem in items:
                        items.pop(poppedItem)
            q.append(c)
            items[c] = c
                
            maxLen = max(maxLen, len(q))
            print(list(q))
        
        return maxLen,q
Solution=Solution()
t=Solution.lengthOfLongestSubstring( "pwwkew")
print(t)
#yukardaki çözüm binim ama bu çözümün algoritması daha dahi

['p']
['p', 'w']
['w']
['w', 'k']
['w', 'k', 'e']
['k', 'e', 'w']
(3, deque(['k', 'e', 'w']))


In [3]:
from time import time
start=time()
def eklemek(A,li):
    c=0
    liste=[]
    sayı=li[-1]//len(A)+1#       بصير نعمل كمان A*sayı
    while c<sayı:
        liste.extend(A)
        c+=1
    return liste
def toplama(k):
    top=0
    for i in range(len(k)):
        top+=k[i]
    return top
def solve(A, R, L):
    liste=[[i,j] for i,j in zip(L,R)]
    lst=[]
    for i in liste:
        list1=eklemek(A,i)
        sayı1=i[0]-1
        sayı2=i[-1]
        list2=list1[sayı1:sayı2]
        toplam=toplama(list2)
        lst.append(toplam)
    return lst
T = int(input())
for _ in range(T):
    N = int(input())
    A = list(map(int, input().split()))
    Q = int(input())
    L = list(map(int, input().split()))
    R =list(map(int, input().split()))
    out_ = solve(A, R, L)
    print (f"elemanların toplamı= {' '.join(map(str, out_))}")
end=time()
print(f"zaman süresi= {end-start}")


1
3
4 1 5
3
1 3 9
4 7 10
elemanların toplamı= 14 19 9
zaman süresi= 23.36400818824768


In [22]:
class Solution(object):
    def rotate(self,s,b):
        s=" ".join(s)
        liste=s.split()
        size=len(liste)
        for j in range(b):
            l=liste[size-1]
            for i in range(size-2,-1,-1):
                liste[i+1]=liste[i]
            liste[0]=l
        return "".join(liste)
    def add(self,s,a):
        new_number=""
        for i in range(1,len(s),2):
            new_number+=s[i-1]+str((int(s[i])+a)%10)
        return new_number
    def findLexSmallestString(self, a, b):
        s="1"
        while len(s)%2!=0 or len(s)>9:
            s=input("bir string sayı olarak giriniz: ")
        seen = set()
        need = list()
        need.append(s)

        while need:
            curr = need.pop()
            if curr not in seen:
                # add current string to seen                 
                seen.add(curr)
                # add next two cases into waiting queue
                need.extend([self.add(curr,a),self.rotate(curr,b)])
        print(seen)
        return min(seen)
a = int(input()); b = int(input())    
Solution=Solution()
t=Solution.findLexSmallestString(a,b)
print(t)


9
2
bir string sayı olarak giriniz: 5525
{'5525', '2050', '5929', '2454', '2555', '5222', '2353', '2151', '5828', '5020', '5323', '5424', '2757', '5727', '2959', '2656', '5626', '5121', '2858', '2252'}
2050


In [52]:
from collections import deque 
class Solution:
    def maxSlidingWindow(self, nums, k):
        q = deque()
        res = []
        for i in range(len(nums)):
            while q and nums[i] >= nums[q[-1]]:
                q.pop()
            q.append(i) # from large to small
            if q[0] <= i-k: # check if the head of q is valid
                q.popleft() 
            if i+1 >= k: # when q is equal to k, add the first num
                res.append(nums[q[0]])
            print(q)
            print(res)
        return res
nums = [1,3,-1,-3,5,3,6,7];k = 3
solution=Solution()
new_liste=solution.maxSlidingWindow(nums,k)
print(new_liste)

deque([0])
[]
deque([1])
[]
deque([1, 2])
[3]
deque([1, 2, 3])
[3, 3]
deque([4])
[3, 3, 5]
deque([4, 5])
[3, 3, 5, 5]
deque([6])
[3, 3, 5, 5, 6]
deque([7])
[3, 3, 5, 5, 6, 7]
[3, 3, 5, 5, 6, 7]


In [71]:
def BK(nums):
    for j in range(1,len(nums)):
        number=nums[0]
        if number<nums[j]:
            return "büyümek"
        elif number>nums[j]:
            return "küçültmek"
def küçültmek(nums):
    i=0
    for j in range(1,len(nums)):
        number=nums[i]
        if number<nums[j]:
            return False
        else:
            i+=1
    return True
def büyümek(nums):
    i=0
    for j in range(1,len(nums)):
        number=nums[i]
        if number>nums[j]:
            return False
        else:
            i+=1
    return True
def isMonotonic(nums):
    sonuç=BK(nums)
    i=0
    if sonuç=="büyümek":
        return büyümek(nums)
    else:
        return küçültmek(nums)
nums = [1,3,2]
print(isMonotonic(nums))
            

False


In [20]:
from numpy.random import randint as ra
def matrixReshape(mat, r, c):
    if r*c > len(mat)*len(mat[0]) or  r*c < len(mat)*len(mat[0]):
        return mat
    liste=[] 
    row=[]
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            if c>len(row):
                row.append(mat[i][j])
                if c==len(row):
                    satır=row
                    liste.append(satır)
                    row=[]
                    
    return liste
matrix=ra(1,9,size=(4,3))
print(matrix)
print(matrixReshape(matrix,2,6))

[[3 4 7]
 [4 3 7]
 [1 2 8]
 [5 4 5]]
[[3, 4, 7, 4, 3, 7], [1, 2, 8, 5, 4, 5]]


In [62]:
from numpy.random import randint as ra
from numpy import array
class solution:
    def __init__(self):
        self.liste=[]
    def diyagonal(self,mat,i,j):
        k=[]
        while i<len(mat) and j>=0:
            k.append(mat[i][j])
            i+=1
            j-=1
        return k
    def aktarmak(self, mat):
        c=1
        for j in range(len(mat[0])):
            l=self.diyagonal(mat,0,j)
            if c%2==0:
                self.liste.extend(l)
            else:
                self.liste.extend(l[::-1])
            c+=1
        for i in range(1,len(mat)):
            l=self.diyagonal(mat,i,len(mat[0])-1)
            if c%2==0:
                self.liste.extend(l)
            else:
                self.liste.extend(l[::-1])
            c+=1
                
        return self.liste
matrix=ra(1,15,size=(3,3))
print(matrix)
solution=solution()
lis=solution.aktarmak(matrix)
print(array(lis))
#بنضيف الاقطار مرة من تحت لفوق ومرة من فوق لتحت

[[10  8  3]
 [ 9  5  2]
 [11  5  9]]
[10  8  9 11  5  3  2  5  9]


In [77]:
import numpy
def sıralama(mat,i,j):
    while i<row_size and j<col_size:
        oi=i+1
        oj=j+1
        while oi<row_size and oj<col_size:
            if mat[i][j]>mat[oi][oj]:
                mat[i][j],mat[oi][oj]=mat[oi][oj],mat[i][j]
            oi+=1
            oj+=1
        i+=1
        j+=1
def diyagonal(mat):
    global row_size, col_size

    col_size=len(mat[0])
    row_size=len(mat)
    for j in range(col_size):
        sıralama(mat,0,j)
    for i in range(1,row_size):
        sıralama(mat,i,0)
    return mat
arr=array([[5,7,8,4],[1,6,9,11],[8,5,1,4],[7,0,3,0]])
print(f"{arr}\n")
print(diyagonal(arr))
#ترتيب الاقطار

[[ 5  7  8  4]
 [ 1  6  9 11]
 [ 8  5  1  4]
 [ 7  0  3  0]]

[[ 0  4  8  4]
 [ 1  1  7 11]
 [ 0  3  5  9]
 [ 7  8  5  6]]


In [34]:
from numpy.random import randint as ra
from math import floor
class Solution(object):
    def __init__(self,m,n):
        self.row=m
        self.col=n
        self.mat=ra(0,1,size=(self.row,self.col))
    def toplama(self,img,i,j):
        toplam=0
        count=0
        for o in range(-1,2):
            if o+i>=0 and o+i<self.row:
                for u in range(-1,2):
                    if u+j>=0 and u+j<self.col:
                        toplam+=img[o+i][u+j]
                        count+=1
                    else:
                        pass
            else:
                pass
        return floor(toplam/count)#floor=int
    def imageSmoother(self, img):
        for i in range(self.row):
            for j in range(self.col):
                self.mat[i][j]=self.toplama(img,i,j)
        return self.mat 
satır_sütün=list(map(int,input().split()))
satır=satır_sütün[0]
sütun=satır_sütün[1]
img=ra(1,100,size=(satır,sütun))#bir matris verilir
print(f"{img}\n")
solution=Solution(satır,sütun)
yeni_mat=solution.imageSmoother(img)
print(yeni_mat)
#birinci nokta=(84+73+21+17)/4 ...

2 4
[[17 73 73 54]
 [21 84  4 62]]

[[48 45 58 48]
 [48 45 58 48]]


In [18]:
from numpy import array
class solution(object):
    def rotate(self, matrix):
        mat=[]
        for i in range(len(matrix[0])):
            liste=[matrix[j][i] for j in range(len(matrix))]
            mat.append(liste[::-1])
        return array(mat)
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix=array(matrix)
print(f"{matrix}\n")
so=solution()
yeni_matrix=so.rotate(matrix)
print(yeni_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [2]:
from numpy.random import randint as ra
from numpy import array
class solution(object):
    def __init__(self):
        self.indexler=[]
    def aramak(self,matrix,i,j):
        for o in range(len(matrix[0])):
            if matrix[i][o]==0 :
                continue
            matrix[i][o]=0
            self.indexler.append((i,o))
        for u in range(len(matrix)):
            if matrix[u][j]==0:
                continue
            matrix[u][j]=0
            self.indexler.append((u,j))        
    def setZeroes(self, matrix):
        for i in range(len(matrix)):
            for j in range(len(matrix[0])):
                if (i,j) not in self.indexler and matrix[i][j]==0:
                    self.aramak(matrix,i,j)
        return matrix
matrix=ra(0,10,size=(3,4))
#matrix=[[0,1,2,0],[3,4,5,2],[1,3,1,5]]
matrix=array(matrix)
print(f"{matrix}\n")
solution=solution()
sol=solution.setZeroes(matrix)
print(sol)
print("operation accomplished successfully")

[[8 1 5 4]
 [2 0 9 8]
 [4 3 0 9]]

[[8 0 0 4]
 [0 0 0 0]
 [0 0 0 0]]
operation accomplished successfully


In [8]:
class Solution:
    def __init__(self):
        self.liste=[]
    def toplam(self,top_liste):
        toplam=0
        for i in range(len(top_liste)):
            toplam+=top_liste[i]
        return toplam
    def generate(self, numRows):
        li=[1]
        self.liste.append(li)
        for i in range(numRows-1):
            lis=[1]
            for j in range(i):
                k=li[j:j+2]
                lis.append(self.toplam(k))
            lis.append(1)
            self.liste.append(lis)
            li=lis
        return self.liste
solution=Solution()
sayı=int(input("bir sayı giriniz: "))
t=solution.generate(sayı)
print(t)
#مثلث باسكال            


bir sayı giriniz: 5
[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]


In [16]:
dizi = [0, 0, 1, 1, 1, 2, 2, 3, 3, 4]
t=0
for i in range(1,len(dizi)):
    if dizi[i] in dizi[0:i]:
        dizi[i]="_"
    elif dizi[i] not in dizi[0:i]:
        if dizi[i-1] == "_":
            dizi[t+1]=dizi[i]
            dizi[i]="_"
            t+=1
        else:
            t+=1
    print(dizi)
print(dizi)

[0, '_', 1, 1, 1, 2, 2, 3, 3, 4]
[0, 1, '_', 1, 1, 2, 2, 3, 3, 4]
[0, 1, '_', '_', 1, 2, 2, 3, 3, 4]
[0, 1, '_', '_', '_', 2, 2, 3, 3, 4]
[0, 1, 2, '_', '_', '_', 2, 3, 3, 4]
[0, 1, 2, '_', '_', '_', '_', 3, 3, 4]
[0, 1, 2, 3, '_', '_', '_', '_', 3, 4]
[0, 1, 2, 3, '_', '_', '_', '_', '_', 4]
[0, 1, 2, 3, 4, '_', '_', '_', '_', '_']
[0, 1, 2, 3, 4, '_', '_', '_', '_', '_']


In [18]:
array = [9, -2, -9, 11, 56, -12, -3]
liste=[]
for i in range(len(array)):
    if i%2==0:
        liste.append((array[i])**2)
    else:
        liste.append(array[i])
print(liste)        

[81, -2, 81, 11, 3136, -12, 9]


In [2]:
class s(object):
    k=4
    alan=0
    def area(self):
        self.alan=self.k**2
        print("area= ",self.alan)
s4=s()
s4.area()

area=  16


In [1]:
def toplama_çarpma(n):
    top=0
    çarp=1
    while n>0:
        last_step=n%10
        n=int((n-last_step)/10)
        top+=last_step
        çarp*=last_step
    return ç
n=int(input())
print(toplama_çarpma(n))

234
(9, 24)


In [23]:
def isAnagram(s, t):
    if len(s)!=len(t):
        return False
    ls=list(map(str,s))
    lt=list(map(str,t))
    for i in range(len(s)):
        if ls[i] in lt:
            index=lt.index(ls[i])
            ls[i]=0
            lt[index]=0
        else:
            return False
    return True
s=input();t=input()
print(isAnagram(s,t))

abba
abab
True


In [141]:
def firstMissingPositive(nums):
    """
    :type nums: List[int]
    :rtype: int
    """

    nums.sort()
    print(nums)
    count = 1
    for i in nums:
        if(i<count):
            continue
        elif(count!=i):

            return count
        else:
            count+=1

    return count
y=firstMissingPositive([-2,-4,0,1,2,5,9])
print(y)

[-4, -2, 0, 1, 2, 5, 9]
3


In [149]:
def findDisappearedNumbers(nums):
    liste=[]
    count=1
    nums.sort()
    print(nums)
    for i in range(len(nums)):
        if count not in nums:
            liste.append(count) 
        count+=1
    return liste
nums = [4,3,2,7,8,2,3,1]
print(max(nums))
t=findDisappearedNumbers(nums)
print(t)
#hash table

8
[1, 2, 2, 3, 3, 4, 7, 8]
[5, 6]


In [1]:
from numpy.random import randint as arr
light=int(input())
matrix=arr(0,10,size=(light,light))
print(matrix)
print()
def diagonalSort(mat):

    xl, yl = len(mat), len(mat[0])
    t = [ [] for i in range( xl+yl ) ]
    print(f"{t}\n")

    for i in range(xl):
        for j in range(yl):
            t[i - j].append(mat[i][j])
    print(f"{t}\n")
    for l in t:
        l.sort(reverse=True)
    print(f"{t}\n")
    for i in range(xl):
        for j in range(yl):
            mat[i][j] = t[i-j].pop()

    return mat
mat=diagonalSort(matrix)
print(mat)
#harika bir çözüm

4
[[2 6 9 4]
 [7 5 3 2]
 [4 9 0 9]
 [4 3 3 7]]

[[], [], [], [], [], [], [], []]

[[2, 5, 0, 7], [7, 9, 3], [4, 3], [4], [], [4], [9, 2], [6, 3, 9]]

[[7, 5, 2, 0], [9, 7, 3], [4, 3], [4], [], [4], [9, 2], [9, 6, 3]]

[[0 3 2 4]
 [3 2 6 9]
 [3 7 5 9]
 [4 4 9 7]]


In [8]:
def sumOddLengthSubarrays(arr):
    t=1
    matrix=[]
    toplam=0
    while t<=len(arr):
        for i in range(0,len(arr)-t+1):
            liste=arr[i:i+t]
            toplam+=sum(liste)
            matrix.append(liste)
        t+=2
    return toplam,matrix
lis=[1,4,2,5,3]
r=sumOddLengthSubarrays(lis)
print(r)

(58, [[1], [4], [2], [5], [3], [1, 4, 2], [4, 2, 5], [2, 5, 3], [1, 4, 2, 5, 3]])


In [10]:
def moveZeroes(nums):
    def k(x):
        return x
    liste=list(filter(k,nums))
    uz=len(liste)
    liste+=[0]*uz
    return liste
lis=[0,1,0,3,12]
t=moveZeroes(lis)
print(t)

[1, 3, 12, 0, 0, 0]


In [21]:
def minimumCardPickup(cards):
    if len(cards)==len(set(list(cards))):
        return -1
    enb=len(cards)
    t=[]
    for i in range(len(cards)-1):
        number1=cards[i]
        for j in range(i+1,len(cards)):
            number2=cards[j]
            if number1==number2 and number1%2==0:
                liste=cards[i:j+1]
                if len(liste)<=enb:
                    enb=len(liste)
                    t=liste
                    break
    return enb,t

k=[77,10,11,51,69,83,33,94,0,42,86,41,65,40,72,8,53,31,43,22,9,94,45,80,40,0,84,34,76,28,7,79,80,93,20,82,36,74,82,89,74,77,27,54,44,93,98,44,39,74,36,9,22,57,70,98,19,68,33,68,49,86,20,50,43]
print(minimumCardPickup(k))

(3, [68, 33, 68])


In [27]:
from numpy.random import randint as ra
mat=ra(1,11,size=(5,5))
print(mat)
for i in range(len(mat)):
    toplam=sum(mat[i])
    print(f"satır toplamı={toplam}")

mat2=ra(1,10,size=(5,5))    

    


[[ 5  8  7  4  9]
 [10  1  3  5  5]
 [ 6 10  8  1  8]
 [ 6 10  8  2  7]
 [ 5  5  3  5  2]]
satır toplamı=33
satır toplamı=24
satır toplamı=33
satır toplamı=33
satır toplamı=20


In [2]:
#its binary search tree(BST) code 
class Node:
    def __init__(self,data,left=None,right=None):
        self.data=data
        self.left=left
        self.right=right
class BST:
    def __init__(self):
        self.root=None
    def search(self,data):
        tmp=self.root
        while tmp != None:
            if tmp.data==data:
                return True
            elif tmp.data>data:
                tmp=tmp.left
            else:
                tmp=tmp.right
        return False
        
    def inorder(self,current):
        if current==None:
            return 
        self.inorder(current.left)
        print(current.data)
        self.inorder(current.right)
    def preorder(self,current):
        if current==None:
            return 
        print(current.data) 
        self.preorder(current.left)
        self.preorder(current.right)
    def postorder(self,current):
        if current==None:
            return 
        self.preorder(current.left)
        self.preorder(current.right)
        print(current.data)
    def insertion(self,current,node_data): 
        if current==None:
            return node_data 
        if node_data.data<current.data:
            current.left = self.insertion(current.left, node_data)
        else:
            current.right = self.insertion(current.right, node_data)
        return current
    def add(self,d):
        node_data=Node(d)
        if self.root==None:
            self.root=node_data
        else:
            self.insertion(self.root,node_data)
    def loop(self,liste):
        for i in range(len(liste)):
            self.add(liste[i])
    def to_print(self):
        if self.root==None:
            print("ağacımız boş")
        else:
            current=self.root
            self.preorder(current)
    def findmin(self,current):
        current=current.right
        while current.left!=None:
            current=current.left
        min_data=current.data
        return min_data
    def deletion(self,current,node_data):
        if current==None:
            return None
        if current.data==node_data.data:  
            if current.left==None and current.right==None:
                print(f"silineccek eleman={current.data}")
                return None
            elif current.left==None and current.right!=None:
                print(f"silineccek eleman={current.data}")
                current=current.right
                return current
                
            elif current.left!=None and current.right==None:
                print(f"silineccek eleman={current.data}")
                current=current.left
                return current
            else:
                print(f"silineccek eleman={current.data}")
                min_data=self.findmin(current)
                current.data=min_data
                min_node=Node(min_data)
                current.right=self.deletion(current.right,min_node)
                return current
        if current.data<node_data.data:
            current.right=self.deletion(current.right,node_data)
        elif current.data>node_data.data:
            current.left=self.deletion(current.left,node_data)
        return current
    def delete(self,data):
        node_data=Node(data)
        self.deletion(self.root,node_data)

bst=BST()
#iste=[6,1,8,3,5,10,7]  
liste=[7,4,2,6,10,9,12,8,9.5,11,15]
bst.loop(liste)
bst.to_print()
print()
bst.delete(10)
bst.delete(15)
bst.to_print()
        

7
4
2
6
10
9
8
9.5
12
11
15

silineccek eleman=10
silineccek eleman=11
silineccek eleman=15
7
4
2
6
11
9
8
9.5
12


In [9]:
from collections import Counter


class NodeTree:
    def __init__(self, left=None, right=None):
        self.left = left
        self.right = right
    def children(self):
        return self.left, self.right

    def __str__(self):
        return self.left, self.right
def huffman_code_tree(node, binString=''):

    if type(node) is str:
        return {node: binString}
    (l, r) = node.children()
    d = dict()
    d.update(huffman_code_tree(l, binString + '0'))
    d.update(huffman_code_tree(r, binString + '1'))
    return d


def make_tree(nodes):
    while len(nodes) > 1:
        (key1, c1) = nodes[-1]
        (key2, c2) = nodes[-2]
        nodes = nodes[:-2]
        node = NodeTree(key1, key2)
        nodes.append((node, c1 + c2))
        nodes = sorted(nodes, key=lambda x: x[1], reverse=True)
    return nodes[0][0]


if __name__ == '__main__':
    string = 'BCAADDDCCACACAC'
    freq = dict(Counter(string))
    freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)
    print(freq)
    node = make_tree(freq)
    encoding = huffman_code_tree(node)
    for i in encoding:
        print(f'{i} : {encoding[i]}')

[('C', 6), ('A', 5), ('D', 3), ('B', 1)]
C : 0
B : 100
D : 101
A : 11


In [5]:
def ters_kelime(n):
    string=''
    for i in(n):
        string=i+string
        print(i)
        print("string",string)
    print(string)
ters_kelime('hello')

h
string h
e
string eh
l
string leh
l
string lleh
o
string olleh
olleh


In [5]:
from numpy.random import randint as ra
def merge(arr, l, m, r):
    n1 = m - l + 1
    n2 = r - m

    # انشاء القوائم الفرعية
    L = [0] * (n1)
    R = [0] * (n2)

    # نقل العناصر الى القوائم الفرعية
    for i in range(0, n1):
        L[i] = arr[l + i]
    for j in range(0, n2):
        R[j] = arr[m + 1 + j]

    # مرشحة العناصر من القوائم الفرعية الى القائمة الرئيسية
    i = 0
    j = 0
    k = l

    while i < n1 and j < n2:
        if L[i] <= R[j]:
            arr[k] = L[i]
            i += 1
        else:
            arr[k] = R[j]
            j += 1
        k += 1

    # نقل العناصر المتبقية من القائمة الفرعية الأولى
    while i < n1:
        arr[k] = L[i]
        i += 1
        k += 1

    # نقل العناصر المتبقية من القائمة الفرعية الثانية
    while j < n2:
        arr[k] = R[j]
        j += 1
        k += 1

def merge_sort(arr, l, r):
    if l < r:
        m = (l + (r - 1)) // 2

        # نقسم القائمة الرئيسية الى قوائم فرعية
        merge_sort(arr, l, m)
        merge_sort(arr, m + 1, r)
        merge(arr, l, m, r)
liste=ra(0,10,size=10)
print(liste)
merge_sort(liste,0,len(liste)-1)
print(liste)
print(set(liste))

[0 9 1 6 0 2 8 4 8 3]
[0 0 1 2 3 4 6 8 8 9]
{0, 1, 2, 3, 4, 6, 8, 9}


In [1]:
from numpy.random import randint as ra 
liste=ra(0,10,size=10)
def sorting(liste):
    for i in range(len(liste)):
        index=i
        j=i+1
        while j<len(liste):
            if liste[j]==liste[index]:
                del liste[j]
                continue
            if liste[j]<liste[index]:
                index=j
                j+=1
        liste[index],liste[i]=liste[i],liste[index]
print(liste)

[0 1 3 9 9 6 1 5 6 0]


In [1]:
m=int(input())
liste= []
for i in range(m):
    x = int(input())
    liste.append(x)
print(liste)

6
1
52
8
8
7
7
[1, 52, 8, 8, 7, 7]


In [2]:
liste=list(map(int,input().split()))
print(liste)

5 4    9 5406 6
[5, 4, 9, 5406, 6]


In [3]:
name=" djf  df"
k=name.split()
print(k)

['djf', 'df']


In [23]:
from random import *
liste=[i for i in range(50)] 
lis=sample(liste,12)
print(lis)

[6, 21, 26, 38, 41, 31, 43, 40, 37, 10, 28, 47]


In [20]:
from random import randint as ra
liste=["A","B","C","D","E"]
dic={}
for i in range(len(liste)):
    sayı=ra(10,30)
    dic[liste[i]]=sayı
    print(f"{liste[i]} = {sayı}")


A = 25
B = 27
C = 17
D = 16
E = 21


In [8]:
from random import randint as ra
liste=[ra(0,9) for i in range(6)]
print(liste)
with open("deneme.txt", "w") as f:
    for i in range(len(liste)):
        kelime=input()
        f.write(kelime)

[2, 8, 2, 9, 8, 6]
nour
bassal
dlfkjds
adlşkf
akmelş
abol


In [146]:
from numpy.random import randint as ra
liste=ra(-10,10,size=6)
print(liste)
def maxSubarraySumCircular(nums):
    answer=None
    for i in range(len(nums)):
        liste=[nums[i]]
        for j in range(i+1,len(nums)):
            if nums[j]+sum(liste)>sum(liste):
                liste.append(nums[j])
        if answer==None:
            answer=liste
        else:
            if sum(liste)>sum(answer):
                answer=liste
    return sum(answer),answer
answer=maxSubarraySumCircular(liste)
print(answer)

[ 6 -3 -6  0 -3  2]
(8, [6, 2])


In [3]:
#عدد بواقي القسمة
def commonfactors(a,b):
    liste=[b%i==0 and a%i==0 for i in range(1,min(a,b)+1)]
    return sum(liste),liste
answer=commonfactors(12,6)
print(answer)

(4, [True, True, True, False, False, True])


In [11]:
class Solution:
    def __init__(self):
        self.count=0
    def isitprime(self,number):
        for i in range(2,number):
            if number%i==0:
                return False
        return True
    def merge(self,liste,l,r):
        if l<r:
            m=(l+r)//2
            self.merge(liste,l,m)
            self.merge(liste,m+1,r)
        print(liste[l:r+1])
        if len(liste[l:r+1])==1:
            if self.isitprime(liste[l:r+1][0]):
                self.count+=1

    def countPrimes(self,n):
        liste=list(range(2,n))
        l=0
        r=len(liste)-1
        self.merge(liste,l,r)
        return self.count
s=Solution()
number=int(input())
print(s.countPrimes(number))

10
[2]
[3]
[2, 3]
[4]
[5]
[4, 5]
[2, 3, 4, 5]
[6]
[7]
[6, 7]
[8]
[9]
[8, 9]
[6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
4


In [12]:
class Solution:
    def __init__(self):
        self.count=0
    def isitprime(self,number):
        for i in range(2,number):
            if number%i==0:
                return False
        return True
    def merge(self,liste):
        if len(liste)>1:
            m=len(liste)//2  #3
            L=liste[:m]
            R=liste[m:]
            self.merge(L)#[2,3,4,5]
            self.merge(R)#[6,7,8,9]
        print(liste)
        if len(liste)==1:
            if self.isitprime(liste[0]):
                self.count+=1

    def countPrimes(self,n):
        liste=list(range(2,n))
        self.merge(liste)
        return self.count
s=Solution()
number=int(input())
answer=s.countPrimes(number)
print(answer)

10
[2]
[3]
[2, 3]
[4]
[5]
[4, 5]
[2, 3, 4, 5]
[6]
[7]
[6, 7]
[8]
[9]
[8, 9]
[6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
4


In [13]:
def simplifiedFractions(n):
    liste=[]
    lst=[]
    for j in range(2,n+1):
        for i in range(1,j):
            deger=i/j
            print(deger)
            if deger not in liste:
                liste.append(deger)
                lst.append(f"{i}/{j}")
    return lst
n=int(input("enter any number: "))
s=simplifiedFractions(n)
print(s)

enter any number: 4
0.5
0.3333333333333333
0.6666666666666666
0.25
0.5
0.75
['1/2', '1/3', '2/3', '1/4', '3/4']


In [6]:
#السؤال هو انو بدي اكير عدد تكرارو نفس قيمة العدد نفسو واذا ما نوجد رجعلي -1
from random import randint as ra
class Solution:
    def findLucky(self,arr):
        answer=-1
        first=0
        while first<len(arr):
            count=1
            t=first+1
            while t<len(arr):
                if arr[first]==arr[t]:
                    count+=1
                    del arr[t]
                else:
                    t+=1
            if arr[first]==count and count>answer:
                answer=count
            first+=1
        return answer,liste
liste=[ra(0,5) for i in range(6)]     
print(liste)        
s=Solution()
answer=s.findLucky(liste)
print(answer)

[3, 0, 2, 3, 2, 0]
(2, [3, 0, 2])


In [30]:
#مجموع اعداد البينري في الناتج هو العدد المدخل
def minPartitions(liste):
    if sum(liste)>0:
        string=""
        for i in range(len(liste)):
            if liste[i]-1>=0:
                string+=str(1)
                liste[i]=liste[i]-1
            else:
                string+=str(0)
        print(string)

        minPartitions(liste)
    else:
        return
n ="82734"
liste=[int(i) for i in n]
print(liste)
minPartitions(liste)

[8, 2, 7, 3, 4]
11111
11111
10111
10101
10100
10100
10100
10000


In [1]:
# السوال انو بدي دخل مصفوفة من حجم كذا بعدين بختار قيمة لا حرف الان وبقطع المصفوفة على هل اساس بختار بس اكبر رقم وبحطو بمصفوفة جديدة 
from random import randint as ra
from numpy import array as ar
size=int(input())
class Matrix:
    def __init__(self):
        self.liste=[]
        self.matrix=[]
    def kucultmek(self,n,i,j,mat):
        enb=mat[i][j] 
        for a in range(i,i+n):
            for b in range(j,j+n):
                if mat[a][b]>enb:
                    enb=mat[a][b]
        self.liste.append(enb)
        if (len(mat[0])-n)>j:
            self.kucultmek(n,i,j+n,mat)
        elif (len(mat[0])-n)==j:
            self.matrix.append(self.liste)
            self.liste=[] 
            if len(mat)-n>i:
                self.kucultmek(n,i+n,0,mat) 
            else:
                print(ar(self.matrix))
k=Matrix()        
mat=[[ra(0,100)for i in range(size)]for j in range(size)]
print(ar(mat))
n=int(input("n in boyutu giriniz: "))
new_matrix=k.kucultmek(n,0,0,mat)


9
[[  1  85  82  75   2  31  24  21  11]
 [ 34  26  77  16 100   5  47  19  96]
 [ 53   3   9  76  35  63  99  37  98]
 [ 23  30  89  15  18  12  15  33   1]
 [ 22  37  80  88  57  49  23  99  83]
 [ 71   1  98  54  87  93  61  37   7]
 [ 57  86  84  90  50  90   2  89  69]
 [  2  71  43  70  87  26  11  81   7]
 [ 64  40  84  74  18  14  58  15  63]]
n in boyutu giriniz: 3
[[ 85 100  99]
 [ 98  93  99]
 [ 86  90  89]]


In [2]:
# NxN boyutlu bir matris oluşturunuz. Bu matrisi k kat küçültünüz. 2 kat küçültme işlemi aşağıda örneklenmiştir
#N ve k değerlerini kullanıcı girecektir, matris değerleri ise 0-100 aralığındaki tam sayı değerlerinden random elde edilecektir. 

from random import choice as ch
class Sepet:
    def __init__(self):
        self.lis=[1,2,3]
    def __ekleme(self,liste,number):
        new_liste=[1]*number
        liste+=new_liste
        return liste
    def __çıkartma(self,liste,number):
        if len(liste)>=number:
            liste=liste[number:]
        else:
            liste=[]
        return liste
    def işleme(self):
        liste=[[] for i in range(3)]
        c=0
        print(liste)
        while True:
            random_number=ch(self.lis)
            print("rastgele numara",random_number)
            li=liste[c]
            random_liste=[self.__ekleme,self.__çıkartma]
            işlem_liste=ch(random_liste)(li,random_number)
            #print("işlem listesi",işlem_liste)
            #print()
            print(liste,random_number,işlem_liste)
            liste[c]=işlem_liste
            print(liste)
            c+=1
            c=c%3
            print()
            if len(işlem_liste)>=3:
                break
büt_sepet=Sepet()
büt_sepet.işleme()
                



[[], [], []]
rastgele numara 2
[[1, 1], [], []] 2 [1, 1]
[[1, 1], [], []]

rastgele numara 2
[[1, 1], [1, 1], []] 2 [1, 1]
[[1, 1], [1, 1], []]

rastgele numara 1
[[1, 1], [1, 1], [1]] 1 [1]
[[1, 1], [1, 1], [1]]

rastgele numara 1
[[1, 1, 1], [1, 1], [1]] 1 [1, 1, 1]
[[1, 1, 1], [1, 1], [1]]



In [5]:
#dinamic programing 
liste=[None]*500
def dinamic_fibo(n):
    if liste[n]==None:
        if n==0:
            liste[n]=0
        elif n==1:
            liste[n]=1
        else:
            liste[n]=dinamic_fibo(n-1)+dinamic_fibo(n-2)
    return liste[n]
for i in range(10):
    print(dinamic_fibo(i))

0
1
1
2
3
5
8
13
21
34


In [12]:
from numpy.random import randint as rd
class Mat:
    def __init__(self,number):
        self.mat=rd(0,101,size=(number,number))
    def diagonal1(self,matrix):
        sum=0
        liste=[]
        for i in range(len(matrix)):
            sayı=matrix[i][i]
            sum +=sayı
            liste.append(sayı)
        return sum,liste
    def diagonal2(self,matrix):
        sum=0
        liste=[]
        size=len(matrix)
        for i in range(size):
            sayı=matrix[i][size-1-i]
            sum+=sayı
            liste.append(sayı)
        return sum,liste
    
    def operation(self,rakam):
        if rakam==1:
            return self.diagonal1(self.mat)
        elif rakam==2:
            return self.diagonal2(self.mat)
        else:
            raise Exception("The transaction number you entered could not be found!,please try again")
    def print_mat(self):
        print(self.mat)
        print()
m=Mat(6)
m.print_mat()
print(f"kulanıcı 1 girerse: {m.operation(1)}")
print(f"kulanıcı 2 girerse: {m.operation(2)}")

[[ 77  72  28  90 100  73]
 [ 73   6  54 100  73  49]
 [ 59   1  98   0  62  53]
 [ 88  12  64  79  64  66]
 [  1  70  68  62  81  46]
 [ 66  31  47  31  32  10]]

kulanıcı 1 girerse: (351, [77, 6, 98, 79, 81, 10])
kulanıcı 2 girerse: (346, [73, 73, 0, 64, 70, 66])


In [ ]:
def şifre_doğrulama(şifre):
    rakamlar_listesi=list(range(0,9))
    rakamlar_listesi=list(map(str,rakamlar_listesi))
    if len(şifre)!=9:
        return False
    for i in şifre:
        i in rakamlar_listesi:
            return True
    return False
counter=0
while counter<3
    şifreyi_gir=input()
    if şifre_doğrulama(şifreyi_gir):
        print("şifreniz doğrudur")
    else:
        counter+=1
    if counter==3:
        print("şifreniz bloke edilmiş")

In [18]:
def ilkharfibüyük(cümle):
    liste=[]
    for i in range(len(cümle)):
        if i==1:
            liste.append(cümle[i].upper())
        else:
            liste.append(cümle[i])
    return "".join(liste)
def herkelime(cümle):
    k=cümle.split()
    liste=[]
    for i in range(len(k)):
        kelime=k[i]
        ilkharf=kelime[0].upper()
        h=kelime[1:]
        f=ilkharf+h
        liste.append(f)
    return " ".join(liste)
def tambüyük(cümle):
    cümle_upper = string.upper()
    return cümle_upper
def tamküçük(cümle):
    cümle_lower = cümle.lower()
    return cümle_lower
k=tamküçük("bdjsf ldjfs")
print(k)

bdjsf ldjfs


In [7]:
"a".upper()

'A'

In [15]:
string = "hello, world!"
string_upper = string.upper()
print(string_upper)

HELLO, WORLD!


In order to celebrate Women's day, Stella started playing with string S. She needs to know the maximum number of characters between any 2 same characters in the string.

As she is busy in playing, help her for the same.

If there are no 2 same characters in the string, print 1.

Note: String is composed of lowercase letters of the Latin alphabet.

In [13]:
T=int(input())
for i in range(T):
    S=list(input().lower())
    max_size=-1
    dic={}
    for i in range(len(S)):
        if S[i] not in dic:
            dic[S[i]]=i
        else:
            size=i-dic[S[i]]-1
            if size>max_size:
                max_size=size
            dic[S[i]]==i

    if max_size==-1:
        print(-1)
    else:
        print(max_size)
    


2
aba
1
babcddc
2


Input: nums = [[1,2,3],[4,5,6],[7,8,9]]

Output: [1,4,2,7,5,3,8,6,9]


Input: nums = [[1,2,3,4,5],[6,7],[8],[9,10,11],[12,13,14,15,16]]

Output: [1,6,2,8,7,3,9,4,12,10,5,13,11,14,15,16]

In [10]:
class Solution:
    def __init__(self):
        self.liste=[]
        
    def find_up_rows(self,i,j,nums):
        while i>=0:
            try:
                value=nums[i][j]
                self.liste.append(value)
            except:
                pass
            i-=1
            j+=1
    
    def find_up_columns(self,i,j,nums):
        while j<len(nums):
            try:
                value=nums[i][j]
                self.liste.append(value)
            except:
                pass
            i-=1
            j+=1

        
    def findDiagonalOrder(self,nums): 
        for i in range(len(nums)):
            self.find_up_rows(i,0,nums)
        
        for j in range(1,len(nums)):
            self.find_up_columns(len(nums)-1,j,nums)
        
        return self.liste
nums =[[6],[8],[6,1,6,16]]
s=Solution()           
print(s.findDiagonalOrder(nums))

[6, 8, 6, 1, 6]


In [15]:
nums = [[1,2,3],[4,5,6],[7,8,9]]
temp = [(i+j, j, i) for i in range(len(nums)) for j in range(len(nums[i]))]
temp.sort()
temp

[(0, 0, 0),
 (1, 0, 1),
 (1, 1, 0),
 (2, 0, 2),
 (2, 1, 1),
 (2, 2, 0),
 (3, 1, 2),
 (3, 2, 1),
 (4, 2, 2)]

In [9]:
class Solution:
    def __init__(self):
        self.liste=[]
        self.vowels=["a","e","i","o","u"]
    def __countvowel(self,query,words):
        counter=0
        for i in words[query[0]:query[1]]:
            word=i
            first_little=word[0]
            last_little=word[-1]
            if last_listtle==first_little and last_little in self.vowels:
                counter+=1
        return counter
    def vowelStrings(self, words: List[str], queries: List[List[int]]) -> List[int]: 
        for i in queries:
            counter=self.__countvowel(i,words)
            if counter !=0:
                self.liste.append()
        return self.liste

NameError: name 'List' is not defined

In [11]:
words = ["aba","bcb","ece","aa","e"]
print(words[1:4])


['bcb', 'ece', 'aa']


In [13]:
words=["b","rmivyakd","kddwnexxssssnvrske","vceguisunlxtldqenxiyfupvnsxdubcnaucpoi","nzwdiataxfkbikbtsjvcbjxtr","wlelgybcaakrxiutsmwnkuyanvcjczenuyaiy","eueryyiayq","bghegfwmwdoayakuzavnaucpur","ukorsxjfkdojcxgjxgmxbghno","pmgbiuzcwbsakwkyspeikpzhnyiqtqtfyephqhl","gsjdpelkbsruooeffnvjwtsidzw","ugeqzndjtogxjkmhkkczdpqzwcu","ppngtecadjsirj","rvfeoxunxaqezkrlr","adkxoxycpinlmcvmq","gfjhpxlzmokcmvhjcrbrpfakspscmju","rgmzhaj","ychktzwdhfuruhpvdjwfsqjhztshcxdey","yifrzmmyzvfk","mircixfzzobcficujgbj","d","pxcmwnqknyfkmafzbyajjildngccadudfziknos","dxmlikjoivggmyasaktllgmfhqpyznc","yqdbiiqexkemebyuitve"]
liste=[]
vowels=["a","e","i","o","u"]
for i in words[5:22]:
    word=i
    if word[-1] in vowels and word[0] in vowels:
        liste.append(word)
print(liste)

['ukorsxjfkdojcxgjxgmxbghno', 'ugeqzndjtogxjkmhkkczdpqzwcu']


In [1]:
class Solution:
    def __init__(self):
        self.top_zero=0
    def fourSumCount(self, nums1, nums2, nums3, nums4):
        dic={}
        liste=[]
        l=[]
        for i in range(len(nums1)):
            for j in range(len(nums2)):
                top=nums1[i]+nums2[j]
                if top not in liste:
                    liste.append(top)
                    dic[top]=1
                else:
                    dic[top]+=1

        for i in range(len(nums3)):
            for j in range(len(nums4)):
                value=nums3[i]+nums4[j]
                if value>0:
                    inverse_value=-abs(value)
                if value<0:
                    inverse_value=abs(value)
                elif value==0:
                    inverse_value=0
                if inverse_value in liste:
                    l.append((value,inverse_value))
                    self.top_zero+=dic[inverse_value]
        return l,liste
nums1 = [1,2]
nums2 = [-2,-1]
nums3 = [-1,2]
nums4 = [0,2]
s=Solution()
ans=s.fourSumCount(nums1,nums2,nums3,nums4)
print(ans)

([(-1, 1), (1, -1)], [-1, 0, 1])


In [41]:
def minFlips(a, b, c):
    flips = 0
    while a > 0 or b > 0 or c > 0:
        bit_a = a & 1
        bit_b = b & 1
        bit_c = c & 1

        if bit_c == 0:
            flips += (bit_a + bit_b)  
        else:
            if bit_a == 0 and bit_b == 0:
                flips += 1  

        a >>= 1
        b >>= 1
        c >>= 1

    return flips
ans=minFlips(13,1,7)
print(ans)

2


In [42]:
def minFlips(a, b, c):
    count=0
    while a!=0 or b!=0 or c!=0:
        a,kalan_a=divmod(a,2)
        b,kalan_b=divmod(b,2)
        c,kalan_c=divmod(c,2)
        if kalan_a==kalan_c and kalan_b==kalan_c:
            pass
        elif (kalan_a==kalan_c or kalan_b==kalan_c) and kalan_c==0:
            count+=1
        elif kalan_a!=kalan_c and kalan_b!=kalan_c and kalan_a==1:
            count+=2
        elif kalan_a!=kalan_c and kalan_b!=kalan_c and kalan_a==0:
            count+=1

    return count
ans=minFlips(12,1,7)
print(ans)

2


In [26]:
def converting(s,i,j):
    new_s=[]
    for a in range(i+1,j):
        new_s.append(chr(ord(s[a])-1))
    if len(s)==j-i-1:
        return "".join(new_s)
    elif i==-1:
        return "".join(new_s)+"a"+s[j+1:]
    elif j==len(s):
        return s[:i]+"a"+"".join(new_s)
    else:
        return s[:i]+"a"+"".join(new_s)+"a"+s[j+1:]
def smallestString(s):
    i,j=None,None
    liste=[]
    length=len(s)
    for a in range(length):
        if s[a]=="a":
            if i==None:
                i=a
                liste.append((i,-1,i))
            elif j==None:
                j=a
                liste.append((j-i-1,i,j))
            else:
                i=j
                j=a
                liste.append((j-i-1,i,j))

        if a==length-1 and s[a]!="a" and i!=None:
            liste.append((a-i-1,i,len(s)))
    
    liste.sort()
    if not liste:
        return converting(s,-1,length)
    else:
        k=liste[-1]
        print(k)
        return converting(s,k[1],k[2])
    
print(smallestString("leetcode"))            

kddsbncd


In [3]:
class Game:
    def __init__(self,n):
        self.size=n
        self.grid=self.rectangular_grid(n)
        self.s=self.separation(self.grid)
        self.fireworks=self.s[0]
        self.empties=self.s[1]
        self.count=0
        self.liste=[]
    def rectangular_grid(self,n):
        mat=[]
        for i in range(n):
            line=" ".join(input())
            line=line.split()
            mat.append(line)
        return mat
    def separation(self,grid):
        fireworks=[]
        empties=[]
        for i in range(self.size):
            for j in range(self.size):
                if grid[i][j]==".":
                    empties.append((i,j))
                else:
                    fireworks.append((i,j))
        return fireworks,empties
    def connection(self,point):
        i,j=point[0],point[1]
        if point in self.empties:
            if point not in self.liste:
                self.liste.append(point)
                self.connection((i-1,j))
                self.connection((i,j-1))
                self.connection((i,j+1))
                self.connection((i+1,j))
        else:
            return 
        
    def destruction(self):
        for point in self.fireworks:
            self.count+=1
            i,j=point[0],point[1]           
            self.connection((i-1,j))
            self.connection((i,j-1))
            self.connection((i,j+1))
            self.connection((i+1,j))
            self.count+=len(self.liste)
            self.liste.clear()
        return self.count
size=int(input())
game=Game(size)
count=game.destruction()
count

4
*..*
..*.
*..*
*..*


66

In [2]:
def rectangular_grid(n):
    mat = []
    for i in range(n):
        line = " ".join(input())
        line = line.split()
        mat.append(line)
    return mat

def separation(grid, size):
    fireworks = []
    empties = set()
    for i in range(size):
        for j in range(size):
            if grid[i][j] == ".":
                empties.add((i, j))
            else:
                fireworks.append((i, j))
    return fireworks, empties

def connection(point, empties, connected,n):
    i, j = point[0], point[1]
    
    if i < 0 or i >=n or j < 0 or j >= n or grid[i][j] != ".":
        return  
    if point in empties:
        if point not in connected:
            connected.add(point)
            connection((i-1, j), empties, connected,n)
            connection((i, j-1), empties, connected,n)
            connection((i, j+1), empties, connected,n)
            connection((i+1, j), empties, connected,n)
    else:
        return

def destruction(fireworks, empties, size):
    count = 0
    for point in fireworks:
        count += 1
        connected = set()
        i, j = point[0], point[1]
        connection((i-1, j), empties, connected,size)
        connection((i, j-1), empties, connected,size)
        connection((i, j+1), empties, connected,size)
        connection((i+1, j), empties, connected,size)
        count += len(connected)
    return count

size = int(input())
grid = rectangular_grid(size)
fireworks, empties = separation(grid, size)
count = destruction(fireworks, empties, size)
print(count)

4
*..*
..*.
*..*
*..*
66


In [1]:
def findMaxLength(nums):
    totalsum,hashmap=0,{0:-1}
    res,diff=0,0
    for i in range(len(nums)):
        if(nums[i]==0):
            totalsum-=1
        else:
            totalsum+=1
        try:
            diff=i-hashmap[totalsum]
            if(diff>res):
                res=diff
        except:
            hashmap[totalsum]=i
    return res
liste=[0,0,1]
findMaxLength(liste)

2

In [2]:
s="nour"
s=s[:-2]
s

'no'

In [10]:
from collections import defaultdict
def numEquivDominoPairs(dominoes):
    dic=defaultdict(int) 
    counter=0
    for i in dominoes:
        str_i=list(map(str,i))
        print(str_i)

dominoes = [[1,2],[2,1],[3,4],[5,6]]
numEquivDominoPairs(dominoes)

['1', '2']
['2', '1']
['3', '4']
['5', '6']
